/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;


import java.awt.AWTKeyStroke;

import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author habib.belkacemi
 */
public class Articles extends javax.swing.JFrame {
 
    private String sql;

    /**
     * Creates new form Articles
     */
    public Articles(String bas) {
        base = bas;
        initComponents();
         jComboBox1.addItem(" ");
         
         k=jComboBox1.getComponentCount();
        // JOptionPane.showMessageDialog(null, k);
         jComboBox1.setSelectedItem(k);
       // KeyStroke existingKeyStroke = KeyStroke.getKeyStroke("TAB");
        
// 1. Get default keys
      Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);
//AutoCompleteDecorator.decorate(jComboBox1);
AutoCompleteDecorator.decorate(jComboBox2);
    }

    private void Update_Table_Article( int k) {
        
        try {
                    
           if (k == 0 ) {           
             sql = "select A.NArticle as \"Nom Article\",A.famille as \"Famille\", A.designation as \"Désignation\",F.nom_fournisseur as \"Fourniseur\", A.prix_unitaire as \"Prix Unitaire\", A.marge as \"Marge\", A.tva as \"TVA\", A.prix_vente as \"Prix de Vente\",A.prix_vente+A.prix_vente*A.tva/100 as \"Prix T.T.C\",A.seuil as \"Seuil\", A.stock_f as \"Stock.F\", A.stock_bl as \"Stock.BL\"  from article A, fournisseur F where A.nfournisseur=F.nfournisseur order by a.designation";
           } else {                    
              sql = query;    
           }            
           
          // Rs = St.executeQuery(sql);                      
          // Table_Articles.setModel(DbUtils.resultSetToTableModel(Rs));
           
           tm = new MyTableModel(sql, base);
           Table_Articles.setModel(tm);
           Table_Articles.setDefaultRenderer(Double.class, new TKMntRenderer());
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table articles\n" + e.getMessage());

        }
    }

    private void Deplacer_Table_Articles(int i) {

        try {
        
            txt_Narticle.setText(Table_Articles.getValueAt(i, 0).toString());
            //txt_famille.setText(Table_Articles.getValueAt(i, 1).toString());
            txt_designation.setText(Table_Articles.getValueAt(i, 2).toString());
            txt_id_fournisseur.setText(Table_Articles.getValueAt(i, 3).toString());
            txt_marge.setText(Table_Articles.getValueAt(i, 5).toString());
            txt_prix_unitaire.setText(Table_Articles.getValueAt(i, 4).toString());           
            txt_tva.setText(Table_Articles.getValueAt(i, 6).toString());
            txt_prix_vente.setText(Table_Articles.getValueAt(i, 7).toString());
            txt_seuil.setText(Table_Articles.getValueAt(i, 8).toString());
            txt_stock_f.setText(Table_Articles.getValueAt(i, 9).toString());
            txt_bl_disponible.setText(Table_Articles.getValueAt(i, 10).toString());

            //txtdateNaiss.setText(dt.getValueAt(i, 4).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur déplacement stagiaire\n" + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Narticle = new javax.swing.JTextField();
        txt_designation = new javax.swing.JTextField();
        txt_id_fournisseur = new javax.swing.JTextField();
        txt_marge = new javax.swing.JTextField();
        txt_tva = new javax.swing.JTextField();
        txt_stock_f = new javax.swing.JTextField();
        txt_bl_disponible = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_prix_vente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_seuil = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        txt_prix_unitaire = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txt_prix_ttc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Articles = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_nouveau = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_effacer = new javax.swing.JButton();
        btn_sauvegarder = new javax.swing.JButton();
        btn_imprimer = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btn_rechercher = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        txt_rechercher = new javax.swing.JTextField();
        btn_seuil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des Articles ");
        setBackground(new java.awt.Color(204, 204, 204));
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identification des Articles", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setText("Code Article :");

        jLabel2.setText("Désignation :");

        jLabel3.setText("Code Fournisseur :");

        jLabel4.setText("Prix unitaire :");

        jLabel5.setText("Marge :");

        jLabel6.setText("TVA   :");

        jLabel7.setText("   Stock F.Disponible       :");

        jLabel8.setText("  Stock B.Disponible       :");

        txt_Narticle.setName(""); // NOI18N
        txt_Narticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NarticleActionPerformed(evt);
            }
        });
        txt_Narticle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NarticleKeyReleased(evt);
            }
        });

        txt_designation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_designationFocusLost(evt);
            }
        });
        txt_designation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_designationKeyReleased(evt);
            }
        });

        txt_id_fournisseur.setInputVerifier(new Pass_Verifier_Fournisseur(base));
        txt_id_fournisseur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_id_fournisseurFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_id_fournisseurFocusLost(evt);
            }
        });
        txt_id_fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_fournisseurActionPerformed(evt);
            }
        });

        txt_marge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_marge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_margeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_margeFocusLost(evt);
            }
        });
        txt_marge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_margeKeyTyped(evt);
            }
        });

        txt_tva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tvaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tvaFocusLost(evt);
            }
        });
        txt_tva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tvaKeyTyped(evt);
            }
        });

        txt_stock_f.setEditable(false);
        txt_stock_f.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_stock_f.setEnabled(false);

        txt_bl_disponible.setEditable(false);
        txt_bl_disponible.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_bl_disponible.setEnabled(false);

        jLabel9.setText("Prix de Vente :");

        txt_prix_vente.setEditable(false);
        txt_prix_vente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_prix_vente.setEnabled(false);

        jLabel10.setText("Famille :");

        jLabel11.setText("    Seuil    :");

        txt_seuil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_seuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_seuilKeyTyped(evt);
            }
        });

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txt_prix_unitaire.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_prix_unitaire.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_prix_unitaire.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_prix_unitaireCaretUpdate(evt);
            }
        });
        txt_prix_unitaire.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_prix_unitaireFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_prix_unitaireFocusLost(evt);
            }
        });
        txt_prix_unitaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prix_unitaireKeyTyped(evt);
            }
        });

        jComboBox2.setEditable(true);
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel12.setText("Prix T.T.C      :");

        txt_prix_ttc.setEditable(false);
        txt_prix_ttc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_prix_ttc.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_Narticle, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_stock_f, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bl_disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_id_fournisseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(712, 712, 712))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_prix_unitaire, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_marge, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(414, 414, 414))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_prix_ttc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_tva, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_prix_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(306, 306, 306))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Narticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_id_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_prix_unitaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_marge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prix_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_prix_ttc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stock_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bl_disponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Table_Articles.setForeground(new java.awt.Color(51, 51, 51));
        Table_Articles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        Table_Articles.setShowHorizontalLines(false);
        Table_Articles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ArticlesMouseClicked(evt);
            }
        });
        Table_Articles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_ArticlesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_ArticlesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Articles);

        btn_nouveau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nouveau.setText("Nouveau");
        btn_nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nouveauActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        btn_effacer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_effacer.setText("Supprimer");
        btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_effacerActionPerformed(evt);
            }
        });

        btn_sauvegarder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sauvegarder.setText("Enregistrer");
        btn_sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sauvegarderActionPerformed(evt);
            }
        });

        btn_imprimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setText("Tout");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Famille");

        btn_rechercher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_rechercher.setText("Rechercher");
        btn_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercherActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Famille");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Code");

        txt_rechercher.setEditable(false);
        txt_rechercher.setEnabled(false);

        btn_seuil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_seuil.setText("Seuil");
        btn_seuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seuilActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Etiquettes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btn_nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_effacer)
                .addGap(18, 18, 18)
                .addComponent(btn_sauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_rechercher)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_seuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_imprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_imprimer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_nouveau)
                            .addComponent(btn_modifier)
                            .addComponent(btn_effacer)
                            .addComponent(btn_sauvegarder)
                            .addComponent(btn_rechercher)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_seuil))
        );

        btn_quitter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quitter))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String pilote = "com.mysql.jdbc.Driver";       

        try {
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql1="select profil from user_info where has_login='Yes' and code_activite ='"+base+"'";
            Rs = St.executeQuery(sql1);
            if (Rs.next()) {
                if (Rs.getString("profil").equals("ADMIN")) {                    
                user_profil=true;
                txt_stock_f.setEditable(user_profil);
                txt_stock_f.setEnabled(user_profil);
                txt_bl_disponible.setEditable(user_profil);
                txt_bl_disponible.setEnabled(user_profil);
                }
            }
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }            
            jRadioButton1.setSelected(true);
             fillCombo();
             fillCombo1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        Update_Table_Article(0);
        
    }//GEN-LAST:event_formWindowOpened

    private void transfert() {
        try {
            String var_cnx= "jdbc:mysql://localhost:3306/2014_bu01";
            //var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);          
            St = cnx.createStatement();
            St1 = cnx.createStatement();
             sql = "SELECT Narticle,stock_f, stock_bl, famille FROM article WHERE famille <>'Menage' ";
             String xcode,sql1; 
             Rs = St.executeQuery(sql);
             while (Rs.next() ) {
                xcode = Rs.getString("narticle");
                sql1 = "SELECT stod, stodb FROM tmp_29 WHERE CODART='"+xcode+"'";
                //JOptionPane.showMessageDialog(null, sql1); 
                Rs1 = St1.executeQuery(sql1);
                //JOptionPane.showMessageDialog(null, "salam"); 
                if (Rs1.next()) {
                String fact = Rs1.getString("stod");
                String bl = Rs1.getString("stodb");
                query = "update  article set  stock_f = '" 
                +Integer.parseInt(fact)+"', stock_bl = '"
                +Integer.parseInt(bl)+ 
                "' where narticle = '" + xcode + "'";   
               //JOptionPane.showMessageDialog(null, query);
                St1.executeUpdate(query);
                }
            
                }
               
        } catch (Exception e) {        
            JOptionPane.showMessageDialog(null, "Erreur :" + e.getMessage());
        }
    }
    private void Affiche_Article() {
        
        try {
            String xnfourni="";
             if (Rs.next()) {
                
                String add1 = Rs.getString("narticle");
                txt_Narticle.setText(add1);
                String add2 = Rs.getString("famille");      
                //String add3 = Rs.getString("designation");
                //txt_designation.setText(add3);
                
                for (j=0 ; j < jComboBox1.getItemCount() ; j++) {
                                   
                    if (add2.equals(jComboBox1.getItemAt(j).toString())) {
                
                        break;  
                 }
                }                    
                jComboBox1.setSelectedIndex(j);
                txt_famille1=jComboBox1.getItemAt(j).toString();    
                String add3 = Rs.getString("designation");
                txt_designation.setText(add3);
                String add4 = Rs.getString("nfournisseur");
                txt_id_fournisseur.setText(add4);                        
                String add6 = Rs.getString("marge");
                txt_marge.setText(add6);
                String add7 = Rs.getString("tva");
                txt_tva.setText(add7);
                String add8 = Rs.getString("prix_vente");                
                txt_prix_vente.setText(mntFmt.mntFmt(Double.parseDouble(add8)));  
                stot_ttc = Double.parseDouble(add8.replaceAll(" ", "").replaceAll(",", "."))  *  (1+Double.parseDouble(add7.replaceAll(" ", "").replaceAll(",", "."))/100);
                txt_prix_ttc.setText(mntFmt.mntFmt(Double.parseDouble((stot_ttc.toString()))));
                
                String add9 = Rs.getString("seuil");
                txt_seuil.setText(add9);
                String add10 = Rs.getString("stock_f");
                txt_stock_f.setText(add10);
                String add11 = Rs.getString("stock_bl");
                txt_bl_disponible.setText(add11);                      
                String add5 = Rs.getString("prix_unitaire");                                
               txt_prix_unitaire.setText(mntFmt.mntFmt(Double.parseDouble(add5)));
               String sql = "select * from fournisseur where nfournisseur = '" + add4 + "'";
               
                Rs = St.executeQuery(sql);
                if (Rs.next()) { 
                  xnfourni = Rs.getString("nom_fournisseur");
                }

                for (j=0 ; j < jComboBox2.getItemCount() ; j++) {                                      
                   //int l = jComboBox2.getItemAt(j).toString().indexOf(" ");
                   int l= xnfourni.length();
                   int k = jComboBox2.getItemAt(j).toString().length();               
                  if (k >= l) {             
                   if (xnfourni.equals(jComboBox2.getItemAt(j).toString().substring(0,l))) {  
                         break;  
                      }
                   }
                }
                jComboBox2.setSelectedIndex(j);
            } else {
               vider_champ();
               txt_designation.setText(null);
             }
        } catch (Exception e) {        
            JOptionPane.showMessageDialog(null, "Erreur :" + e.getMessage());
        }    
    }
    private void Affiche_Article_des() {
        
        try {
            String xnfourni="";
             if (Rs.next()) {
                
                String add1 = Rs.getString("narticle");
                txt_Narticle.setText(add1);
                String add2 = Rs.getString("famille");      
                //String add3 = Rs.getString("designation");
                //txt_designation.setText(add3);
                
                for (j=0 ; j < jComboBox1.getItemCount() ; j++) {
                                   
                    if (add2.equals(jComboBox1.getItemAt(j).toString())) {
                
                        break;  
                 }
                }                    
                jComboBox1.setSelectedIndex(j);
                txt_famille1=jComboBox1.getItemAt(j).toString();    
               // String add3 = Rs.getString("designation");
                //txt_designation.setText(add3);
                String add4 = Rs.getString("nfournisseur");
                txt_id_fournisseur.setText(add4);                                               
                String add6 = Rs.getString("marge");
                txt_marge.setText(add6);
                String add7 = Rs.getString("tva");
                txt_tva.setText(add7);
                String add8 = Rs.getString("prix_vente");                
                txt_prix_vente.setText(mntFmt.mntFmt(Double.parseDouble(add8))); 
                stot_ttc = Double.parseDouble(add8.replaceAll(" ", "").replaceAll(",", "."))  *  (1+Double.parseDouble(add7.replaceAll(" ", "").replaceAll(",", "."))/100);
                txt_prix_ttc.setText(mntFmt.mntFmt(Double.parseDouble((stot_ttc.toString()))));
                String add9 = Rs.getString("seuil");
                txt_seuil.setText(add9);
                String add10 = Rs.getString("stock_f");
                txt_stock_f.setText(add10);
                String add11 = Rs.getString("stock_bl");
                txt_bl_disponible.setText(add11);                      
                String add5 = Rs.getString("prix_unitaire");                                
               txt_prix_unitaire.setText(mntFmt.mntFmt(Double.parseDouble(add5)));
               String sql = "select * from fournisseur where nfournisseur = '" + add4 + "'";               
                Rs = St.executeQuery(sql);
                if (Rs.next()) { 
                  xnfourni = Rs.getString("nom_fournisseur");
                }

                for (j=0 ; j < jComboBox2.getItemCount() ; j++) {                                      
                   //int l = jComboBox2.getItemAt(j).toString().indexOf(" ");
                   int l= xnfourni.length();
                   int k = jComboBox2.getItemAt(j).toString().length();               
                   if (k >= l) {
                   if (xnfourni.equals(jComboBox2.getItemAt(j).toString().substring(0,l))) {  
                         //JOptionPane.showMessageDialog(null, jComboBox2.getItemAt(j).toString().substring(0,l));
                         break;  
                      }
                   }
                }
                jComboBox2.setSelectedIndex(j);
             } 
             else {
              vider_champ();
             
        }
        } catch (Exception e) {        
            JOptionPane.showMessageDialog(null, "Erreur :" + e.getMessage());
        }    
    } 
    
    private void Table_ArticlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ArticlesMouseClicked
    
        try {
            int row = Table_Articles.getSelectedRow();
            String Table_click = (Table_Articles.getModel().getValueAt(row, 0).toString());
            String sql = "select * from article where narticle = '" + Table_click + "'";                                 
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
           
            //St = cnx.createStatement();
            Rs = St.executeQuery(sql);
            Affiche_Article();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
    }//GEN-LAST:event_Table_ArticlesMouseClicked


    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    private void Table_ArticlesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_ArticlesKeyPressed
        try {
        char txt_car; 
        txt_car = evt.getKeyChar();
        txt_car = Character.toUpperCase(txt_car);
       //JOptionPane.showMessageDialog(null, txt_car);
        query = "select * from article where designation like '" + txt_car + "%' order by designation";
        //JOptionPane.showMessageDialog(null, sql);
        
        Rs = St.executeQuery(query);        
        if (Rs.next()) {
        Affiche_Article();          
        Update_Table_Article(1);
        }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
}
    }//GEN-LAST:event_Table_ArticlesKeyPressed

    private void Table_ArticlesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_ArticlesKeyReleased

        //if ((evt.getKeyCode() == KeyEvent.VK_UP) ||(evt.getKeyCode() == KeyEvent.VK_DOWN) )

        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
            try {
                int row = Table_Articles.getSelectedRow();
                String Table_click = (Table_Articles.getModel().getValueAt(row, 0).toString());
                String sql = "select * from article where narticle = '" + Table_click + "'";

               // Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
                //St = cnx.createStatement();
                Rs = St.executeQuery(sql);
                Affiche_Article();                  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }


        }

    }//GEN-LAST:event_Table_ArticlesKeyReleased

    private void fillCombo() {
    String sql ="select * from famille_art";
    try {
        
    Rs = St.executeQuery(sql);
    while (Rs.next() ) {
       String nme = Rs.getString("famille");
       jComboBox1.addItem(nme);
    }
    
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la liste jComboBox1\n" + e.getMessage());
            }
    }
     private void fillCombo1() {
    
    String sql ="select * from fournisseur  order by nom_fournisseur";
    //JOptionPane.showMessageDialog(null, sql);
    try {
    jComboBox2.addItem("          ");    
    Rs = St.executeQuery(sql);
    while (Rs.next() ) {
       String nme = Rs.getString("nom_fournisseur");
       //JOptionPane.showMessageDialog(null, nme);
       // String nme1 = Rs.getString("nfournisseur");
       jComboBox2.addItem(nme);
    }
    
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la liste jComboBox1\n" + e.getMessage());
            }
    }
     
     class PassVerifier extends InputVerifier {
         public boolean verify(JComponent input) {
               JTextField tf = (JTextField) input;
               return "pass".equals(tf.getText());
         }
     }

     
    private void btn_sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sauvegarderActionPerformed
        // Effacer les champs de saisie
        try {
            //JOptionPane.showMessageDialog(null, txt_famille1);
            String query = "insert into article values ('"
            +txt_Narticle.getText()+"','"
             //+txt_famille.getText()+"','"
            +txt_famille1+"','"
            +txt_designation.getText().replace("'","''")+"','"
            +txt_id_fournisseur.getText()+"','"
            +prix_unitaire.toString()+"','"
            +txt_marge.getText()+"','"
            +txt_tva.getText()+"','"
             //+txt_prix_vente.getText()+"','"
            +stot_ligne.toString()+"','"
            +txt_seuil.getText()+"','"
           +txt_stock_f.getText()+"','"
            +txt_bl_disponible.getText()+"')";
            //JOptionPane.showMessageDialog(null,query);
           // txt_designation.setText(query);
            St.executeUpdate(query);
            Update_Table_Article(0);
            new_saisie = true;
            JOptionPane.showMessageDialog(null,"Article ajouté !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }

    }//GEN-LAST:event_btn_sauvegarderActionPerformed

    private void txt_NarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NarticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NarticleActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        String tmp = (String)jComboBox1.getSelectedItem();
       
        String sql = "select * from famille_art where famille = '" + tmp + "'";     
        try {
        Rs = St.executeQuery(sql);        
        if (Rs.next()) {
        String add = Rs.getString("famille");
        //txt_famille.setText(add);        
        txt_famille1 = add;
        
        }                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void txt_id_fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_fournisseurActionPerformed
        
        String sql = "select * from fournisseur where nfournisseur = '" + txt_id_fournisseur.getText() + "'";     
        String val = "";
        try {
        val = txt_id_fournisseur.getText();
        JOptionPane.showMessageDialog(null, sql);
        Rs = St.executeQuery(sql);        
        if (Rs.next()) {
             val = Rs.getString("nom_fournisseur");
             JOptionPane.showMessageDialog(null, val);
        }                
        else {
            JOptionPane.showMessageDialog(null, "fournisseur inexistant");
            evt.getSource();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le champ fournisseur \n" + e.getMessage());
        }
        
    }//GEN-LAST:event_txt_id_fournisseurActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
     // String query = "update  article set famille =? , designation =? ,nfournisseur =?, prix_unitaire=?, marge= ?, tva=?, prix_vente =?,seuil=?, stock_f =? , stock_bl =? where narticle = ?" ;        
     try {
          
         cal_prix_vente();
            txt_Narticle.setEditable(false);
            query = "update  article set famille ='"          
            +txt_famille1+"', designation ='"
            +txt_designation.getText().replace("'","''")+"', nfournisseur ='"
            +txt_id_fournisseur.getText()+"', prix_unitaire = '"
            +prix_unitaire.toString()+"',marge ='"
            +txt_marge.getText()+"',tva = '"
            +txt_tva.getText()+"',prix_vente ='"
            +stot_ligne.toString()+"',seuil = '"
            +txt_seuil.getText()+"', stock_f = '" 
            +Integer.parseInt(txt_stock_f.getText())+"', stock_bl = '"
            +Integer.parseInt(txt_bl_disponible.getText())+ 
             "' where narticle = '" + txt_Narticle.getText() + "'";   
            St.executeUpdate(query);            
            Update_Table_Article(0);
            JOptionPane.showMessageDialog(null,"Article Modifié !");
            txt_Narticle.setEditable(true); 
   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la modification table\n" + e.getMessage());

        }    
        
        
        
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_effacerActionPerformed
  
        String query = "delete from article where narticle = '" + txt_Narticle.getText() + "'";
        try {
         //JOptionPane.showConfirmDialog(null, " confirmer Effacer ", query, WIDTH);
            if (JOptionPane.showConfirmDialog(null,"Confimer la suppression", " Effacer", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION )  {
            St.executeUpdate(query);
            Update_Table_Article(0);    
        }
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la suppression\n" + e.getMessage());

        }    
        
        
    }//GEN-LAST:event_btn_effacerActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btn_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercherActionPerformed
                   
         try {
         txt_rechercher.setEditable(true);
         txt_rechercher.setEnabled(true);
         //String query = "select * from article where narticle = '" + txt_rechercher.getText() + "'";  
                  
         if (jRadioButton1.isSelected())  {
            query = "select * from article where narticle = '" + txt_Narticle.getText() + "'";              
            } 
         else {
           query = "select * from article where famille = '" + txt_famille1 + "'";                
              }
         
            Rs = St.executeQuery(query);                        
           if (Rs.next()) {
                String add1 = Rs.getString("narticle");
                txt_Narticle.setText(add1);
                String add2 = Rs.getString("famille");                
                for (j=0 ; j < jComboBox1.getItemCount() ; j++) {  
                    if (add2.equals(jComboBox1.getItemAt(j).toString())) {                
                        break;  
                 }
                }
                jComboBox1.setSelectedIndex(j);                                
                txt_famille1=jComboBox1.getItemAt(j).toString();                
                String add3 = Rs.getString("designation");
                txt_designation.setText(add3);
                String add4 = Rs.getString("nfournisseur");
                txt_id_fournisseur.setText(add4);
                String add6 = Rs.getString("marge");
                txt_marge.setText(add6);
                String add5 = Rs.getString("prix_unitaire");
                txt_prix_unitaire.setText(mntFmt.mntFmt(Double.parseDouble(add5)));            
                String add7 = Rs.getString("tva");
                txt_tva.setText(add7);
                String add8 = Rs.getString("prix_vente");
                txt_prix_vente.setText(mntFmt.mntFmt(Double.parseDouble(add8)));
                stot_ttc = Double.parseDouble(add8.replaceAll(" ", "").replaceAll(",", "."))  *  (1+Double.parseDouble(add7.replaceAll(" ", "").replaceAll(",", "."))/100);
                txt_prix_ttc.setText(mntFmt.mntFmt(Double.parseDouble((stot_ttc.toString()))));
                String add9 = Rs.getString("seuil");
                txt_seuil.setText(add9);
                String add10 = Rs.getString("stock_f");
                txt_stock_f.setText(add10);
                String add11 = Rs.getString("stock_bl");
                txt_bl_disponible.setText(add11);
            }
            
            
            Update_Table_Article(1);
            
            txt_rechercher.setEnabled(false);
            txt_rechercher.setEditable(false);
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la suppression\n" + e.getMessage());

        }    
        txt_rechercher.setEnabled(false);
        txt_rechercher.setEditable(false);
        
    }//GEN-LAST:event_btn_rechercherActionPerformed

    private void btn_nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nouveauActionPerformed
        new_saisie = false;       
        txt_Narticle.setText(null);
        txt_designation.setText(null);
        vider_champ();        
        
    }//GEN-LAST:event_btn_nouveauActionPerformed

    private void vider_champ() 
    {
         jComboBox1.setSelectedIndex(0);
         jComboBox2.setSelectedIndex(0);
         txt_bl_disponible.setText("0");
         //txt_designation.setText(null);
         txt_id_fournisseur.setText(null);
         txt_marge.setText(null);
         txt_prix_unitaire.setText(null);
         txt_prix_vente.setText(null);
         txt_prix_ttc.setText(null);
         txt_rechercher.setText(null);
         txt_seuil.setText(null);
         txt_stock_f.setText("0");
         txt_tva.setText(null);
    
    
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      /*  String tmp = (String)jComboBox1.getSelectedItem();
       JOptionPane.showMessageDialog(null, tmp);
        String sql = "select * from famille_art where famille = '" + tmp + "'";     
        try {
        Rs = St.executeQuery(sql);        
        if (Rs.next()) {
        String add = Rs.getString("famille");
        //txt_famille.setText(add);        
        txt_famille1 = add;
        JOptionPane.showMessageDialog(null, txt_famille1);
        }                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }
        
        */
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txt_prix_unitaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prix_unitaireActionPerformed
         
    }//GEN-LAST:event_txt_prix_unitaireActionPerformed

    private void txt_prix_unitaireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_unitaireKeyTyped
      char kar = evt.getKeyChar();
        
        if ( !(kar >='0' && kar <= '9')){

            if (!( kar ==',' | kar =='.')){
                    evt.consume();
            }
        } else {
        
        }
    }//GEN-LAST:event_txt_prix_unitaireKeyTyped

    private void txt_prix_unitaireFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_unitaireFocusLost
        cal_prix_vente();        
    }//GEN-LAST:event_txt_prix_unitaireFocusLost

    private void txt_margeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_margeFocusLost
        cal_prix_vente();            
    }//GEN-LAST:event_txt_margeFocusLost

    private void txt_margeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_margeKeyTyped
     char kar = evt.getKeyChar();

        if ( !(kar >='0' && kar <= '9')){

            if (!( kar ==',' | kar =='.')){
                    evt.consume();
            }
        } 
    }//GEN-LAST:event_txt_margeKeyTyped

    private void txt_tvaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tvaKeyTyped
       char kar = evt.getKeyChar();

        if ( !(kar >='0' && kar <= '9')){

            if (!( kar ==',' | kar =='.')){
                    evt.consume();
            }
        } 
    }//GEN-LAST:event_txt_tvaKeyTyped

    private void txt_seuilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_seuilKeyTyped
      char kar = evt.getKeyChar();

        if ( !(kar >='0' && kar <= '9')){

            if (!( kar ==',' | kar =='.')){
                    evt.consume();
            }
        } 
    }//GEN-LAST:event_txt_seuilKeyTyped

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
    String tmp = (String)jComboBox2.getSelectedItem();
       
        String sql = "select * from fournisseur where nom_fournisseur = '" + tmp + "'";  
    
        try {
        Rs = St.executeQuery(sql);        
        if (Rs.next()) {
        String add = Rs.getString("nfournisseur");                
        txt_id_fournisseur.setText(add);        
        }                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void txt_id_fournisseurFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id_fournisseurFocusLost
        
      txt_id_fournisseur.setInputVerifier(new Pass_Verifier_Fournisseur(base));
       String sql = "select * from fournisseur where nfournisseur = '" + txt_id_fournisseur.getText() +"'";     
        try {
        Rs = St.executeQuery(sql);        
        if (Rs.next()) {
        //String add = txt_id_fournisseur.getText()+" " + Rs.getString("nom_fournisseur");     
        String add =  Rs.getString("nom_fournisseur");         
        String add1 = txt_id_fournisseur.getText();
        txt_id_fournisseur.setText(add1);        
         
         for (j=0 ; j < jComboBox2.getItemCount() ; j++) {
  
                    if (add.equals(jComboBox2.getItemAt(j).toString())) {
                
                        break;  
                 }
                }
                jComboBox2.setSelectedIndex(j);
                                
                //txt_famille1=jComboBox1.getItemAt(j).toString();                                             
        } 
        /*else { 
        
               JOptionPane.showMessageDialog(null, " Fournisseur Inéxistant ! ");
              
        }*/
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }
        
    }//GEN-LAST:event_txt_id_fournisseurFocusLost

    private void txt_id_fournisseurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_id_fournisseurFocusGained
        //txt_id_fournisseur.setText("");
    }//GEN-LAST:event_txt_id_fournisseurFocusGained

    private void txt_designationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_designationFocusLost
       // txt_designation.setText(txt_designation.getText().replace("'","''"));
    }//GEN-LAST:event_txt_designationFocusLost

    private void txt_margeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_margeFocusGained
        txt_marge.selectAll();
    }//GEN-LAST:event_txt_margeFocusGained

    private void txt_NarticleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NarticleKeyReleased
        try {
             String sql = "select * from article where narticle = '" + txt_Narticle.getText() + "'";
             Rs = St.executeQuery(sql);
             Affiche_Article();
             query=sql;
             Update_Table_Article(1);
                            
           } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
    }//GEN-LAST:event_txt_NarticleKeyReleased

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
       this.dispose();        
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
       try { 
        if (jRadioButton3.isSelected())  {
           sql = "select 1 ";                                         
           //sql = "select * from article order by designation "; 
           sql_sum="select sum(stock_f*prix_unitaire) as som_f_u,sum(stock_bl*prix_unitaire) as som_bl_u,sum(stock_f*prix_vente) as som_f_v,sum(stock_bl*prix_vente) as som_bl_v from article where famille ='"+txt_famille1.toString() +"'";             
           sql_p=" where famille='"+txt_famille1 +"' order by designation";
             txt_sous_titre="Famille : "+txt_famille1;
             } 
         else {
            sql = "select 1 ";                                         
            //sql = "select * from article order by designation "; 
            sql_sum="select sum(stock_f*prix_unitaire) as som_f_u,sum(stock_bl*prix_unitaire) as som_bl_u,sum(stock_f*prix_vente) as som_f_v,sum(stock_bl*prix_vente) as som_bl_v from article order by designation";
            
            sql_p=" order by designation";
            txt_sous_titre="Tout le stock";
        }
        Rs=St.executeQuery(sql_sum);
        if (Rs.next()) {
        jd = JRXmlLoader.load("C:\\outil_dev\\report_art_stock.jrxml");
        JRDesignQuery newquery = new JRDesignQuery();
        newquery.setText(sql);
        jd.setQuery(newquery);
        HashMap hm = new HashMap();
        hm.put("famille_p", txt_famille1);
        hm.put("som_f_u_p",Double.parseDouble((Rs.getString("som_f_u"))));
        hm.put("som_bl_u_p",Double.parseDouble((Rs.getString("som_bl_u"))));
        hm.put("som_f_v_p",Double.parseDouble((Rs.getString("som_f_v"))));
        hm.put("som_bl_v_p",Double.parseDouble((Rs.getString("som_bl_v"))));
        hm.put("sous_titre_p", txt_sous_titre);
        hm.put("sql_p_req",sql_p);
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, hm, cnx);            
        JasperViewer.viewReport(jp, false);          
       } 
       }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_designationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_designationKeyReleased
       /* try {
            // AJOUTER UN TEST POUR SAVOIR SI ON EST EN MODE D UNE NOUVELLE SAISIE OU DE CONSULTATION
            if ( new_saisie) {
            String sql = "select * from article where designation LIKE '" + txt_designation.getText() + "%'";
            //String sql = "select * from article where designation = '" + txt_designation.getText() + "'";
             Rs = St.executeQuery(sql);        
             //if (Rs.next()) {
                       Affiche_Article_des();
               //             }
                       query=sql;
                       Update_Table_Article(1);
            }
           } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }*/
    }//GEN-LAST:event_txt_designationKeyReleased

    private void btn_seuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seuilActionPerformed
       try { 
        if (jRadioButton3.isSelected())  {
           sql = "select 1 "; 
           //sql_sum="select sum(stock_f*prix_unitaire) as som_f_u,sum(stock_bl*prix_unitaire) as som_bl_u,sum(stock_f*prix_vente) as som_f_v,sum(stock_bl*prix_vente) as som_bl_v from article where famille ='"+txt_famille1.toString() +"'"; 
            
           sql_p=" where famille='"+txt_famille1 +"' and seuil >= (stock_f+stock_bl) order by designation";
             txt_sous_titre="Famille : "+txt_famille1;
             } 
         else {
            sql = "select 1 ";                                         
            //sql_sum="select sum(stock_f*prix_unitaire) as som_f_u,sum(stock_bl*prix_unitaire) as som_bl_u,sum(stock_f*prix_vente) as som_f_v,sum(stock_bl*prix_vente) as som_bl_v from article";
            
            sql_p="where seuil >= (stock_f+stock_bl) order by designation";
            txt_sous_titre="Tout le stock";
        }
        //Rs=St.executeQuery(sql_sum);
        //JOptionPane.showMessageDialog(null,sql_p);
       // if (Rs.next()) {
        jd = JRXmlLoader.load("C:\\outil_dev\\report_art_seuil.jrxml");
        JRDesignQuery newquery = new JRDesignQuery();
        newquery.setText(sql);
        jd.setQuery(newquery);
        HashMap hm = new HashMap();
        hm.put("famille_p", txt_famille1);
        //hm.put("som_f_u_p",Double.parseDouble((Rs.getString("som_f_u"))));
        //hm.put("som_bl_u_p",Double.parseDouble((Rs.getString("som_bl_u"))));
        //hm.put("som_f_v_p",Double.parseDouble((Rs.getString("som_f_v"))));
        //hm.put("som_bl_v_p",Double.parseDouble((Rs.getString("som_bl_v"))));
        hm.put("sous_titre_p", txt_sous_titre);
        hm.put("sql_p_req",sql_p);
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, hm, cnx);            
        JasperViewer.viewReport(jp, false);          
       } 
       //}
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
        
        
    }//GEN-LAST:event_btn_seuilActionPerformed

 private void info_etiquette() {
        //String xdt = ((JTextField) date_fact.getDateEditor().getUiComponent()).getText();
        String[] par_prompts = {"Pourcentage remise :"};        
        //String[] par_initial = {"", xdt, ""};
        //String [] message = { "", ""};
        Object[] x = MultiInputPane.showMultiInputDialog(null, par_prompts,  "Complément d'info");
        
        txt_pour = x[0].toString();
        
                
    }      
    
private void publi(){
        try { 
      
             if (txt_Narticle.getText().isEmpty() ) 
          { JOptionPane.showMessageDialog(null,"Veuiller choisir un code article SVP!");
           return;
        }
          
             
           sql = "select narticle, prix_unitaire,  prix_vente, tva, designation from article where narticle='"+txt_Narticle.getText() + "'"; 
        //Rs=St.executeQuery(sql_sum);
        //JOptionPane.showMessageDialog(null,sql);
        info_etiquette();
         if (txt_pour.isEmpty() ) 
          { JOptionPane.showMessageDialog(null,"Veuiller entrer une valeur non null SVP!");
           return;
        }
        
        jd = JRXmlLoader.load("C:\\outil_dev\\report_art_publ.jrxml");
        //jd = JRXmlLoader.load("C:\\outil_dev\\Report_test.jrxml");
        JRDesignQuery newquery = new JRDesignQuery();
        newquery.setText(sql);
        jd.setQuery(newquery);
        HashMap hm = new HashMap();
        
        Double val_pour =Double.parseDouble((txt_pour.toString()));
        hm.put("p_pourcentage", val_pour); 
    
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, hm, cnx);  
      
        JasperViewer.viewReport(jp, false);          
       } 
       //}
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
        
        
    }

    
    private void txt_prix_unitaireCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_prix_unitaireCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prix_unitaireCaretUpdate

    private void txt_prix_unitaireFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_unitaireFocusGained
    txt_prix_unitaire.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prix_unitaireFocusGained

    private void txt_tvaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tvaFocusLost
    cal_prix_vente();
    }//GEN-LAST:event_txt_tvaFocusLost

    private void txt_tvaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tvaFocusGained
        txt_tva.selectAll();
    }//GEN-LAST:event_txt_tvaFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        publi();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void cal_prix_vente(){
    try {
        if ("".equals(txt_prix_unitaire.getText() )){
           txt_prix_unitaire.setText("0");         
       }
         if ("".equals(txt_marge.getText())) {
                 txt_marge.setText("0");
        }
          if ("".equals(txt_tva.getText())) {
                 txt_tva.setText("0");
        }
        stot_ligne = Double.parseDouble(txt_prix_unitaire.getText().replaceAll(" ", "").replaceAll(",", "."))  * (1+Double.parseDouble(txt_marge.getText().replaceAll(" ", "").replaceAll(",", "."))/100);
        stot_ttc = Double.parseDouble(txt_prix_unitaire.getText().replaceAll(" ", "").replaceAll(",", "."))  * (1+Double.parseDouble(txt_marge.getText().replaceAll(" ", "").replaceAll(",", "."))/100)* (1+Double.parseDouble(txt_tva.getText().replaceAll(" ", "").replaceAll(",", "."))/100);
        prix_unitaire=Double.parseDouble(txt_prix_unitaire.getText().replaceAll(" ", "").replaceAll(",", "."));
        txt_prix_vente.setText(mntFmt.mntFmt(Double.parseDouble((stot_ligne.toString()))));
        txt_prix_ttc.setText(mntFmt.mntFmt(Double.parseDouble((stot_ttc.toString()))));
        txt_prix_unitaire.setText(mntFmt.mntFmt(Double.parseDouble((prix_unitaire.toString()))));
       
    }
    catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur calcul prix_vente" + e.getMessage());

        }
    }    
        
    
    /**/
    /**
     * @param args the command line arguments
     */
    public static void Articles(final String pas) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
        
         
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articles(pas).setVisible(true);
            }
        });
    }
    // Déclaration des variables
    private Connection cnx;
    private Statement St,St1;
    private ResultSet Rs,Rs1;
    private boolean new_saisie = true,user_profil=false;
    private int i,j,k;
    private Double stot_ligne,prix_unitaire, stot_ttc ;
    private String base,txt_famille1,query,sql_p,sql_sum,txt_sous_titre,txt_pour;
    MyTableModel tm;
    public JasperDesign jd;
    //private String pilote;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Articles;
    private javax.swing.JButton btn_effacer;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_nouveau;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_rechercher;
    private javax.swing.JButton btn_sauvegarder;
    private javax.swing.JButton btn_seuil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Narticle;
    private javax.swing.JTextField txt_bl_disponible;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_id_fournisseur;
    private javax.swing.JTextField txt_marge;
    private javax.swing.JTextField txt_prix_ttc;
    private javax.swing.JTextField txt_prix_unitaire;
    private javax.swing.JTextField txt_prix_vente;
    private javax.swing.JTextField txt_rechercher;
    private javax.swing.JTextField txt_seuil;
    private javax.swing.JTextField txt_stock_f;
    private javax.swing.JTextField txt_tva;
    // End of variables declaration//GEN-END:variables
}
