/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

/**
 *
 * @author Habib.Belkacemi
 */

//import com.toedter.calendar.JDateChooser;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;




public class Clients extends javax.swing.JFrame {

    /**
     * Creates new form Clients
     */
    public Clients( String bas) {
        base = bas;
        initComponents();
   Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);
    
    
    }
private void Update_Table_Clients() {

        try {
            //String sql = "select Nclient as \"Code Client.\", Raison_sociale as \"Raison Sociale\",adresse as \"Adresse\", contact_person as \"Contact \", Tel as \"Tél \", email as \"Email\", NRC as \"N°R.Comm. \", date_format(date_rc, get_format(date, 'EUR' )) as \"Date R.C \", lieu_rc as \"Lieu R.C\", I_Fiscal as \"Ident.Fiscal\", n_article as \"N°Article\"  from client";
            // ça marche String sql = "SELECT Nclient, Raison_sociale, adresse, contact_person, C_affaire_fact, C_affaire_bl, Date_RC FROM client";
              String sql = "SELECT Nclient, Raison_sociale, adresse, contact_person, C_affaire_fact, C_affaire_bl, NRC,Date_RC, Lieu_RC, I_Fiscal, N_article, Tel, email, commentaire FROM client ORDER BY raison_sociale";    
              //String sql = "SELECT NRC,Date_RC, Lieu_RC, I_Fiscal, N_article, Tel, email, commentaire FROM client";
            //Rs = St.executeQuery(sql);
            //Table_Clients.setModel(DbUtils.resultSetToTableModel(Rs));
            
            tm = new MyTableModel(sql,base);
            Table_Clients.setModel(tm);
            Table_Clients.setDefaultRenderer(Double.class, new TKMntRenderer());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table Clients\n" + e.getMessage());

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        raisonsociale = new javax.swing.JTextField();
        commentaireLabel = new javax.swing.JLabel();
        nclient = new javax.swing.JTextField();
        telLabel = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        IFiscalLabel = new javax.swing.JLabel();
        narticleLabel = new javax.swing.JLabel();
        dateRCLabel = new javax.swing.JLabel();
        lieuRCLabel = new javax.swing.JLabel();
        contactPerson = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        date_rc = new com.toedter.calendar.JDateChooser();
        caffairefact = new javax.swing.JTextField();
        caffairebl = new javax.swing.JTextField();
        nrc = new javax.swing.JTextField();
        lieuRC = new javax.swing.JTextField();
        IFiscal = new javax.swing.JTextField();
        narticle = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        nrcLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        contactPersonLabel = new javax.swing.JLabel();
        adresseLabel = new javax.swing.JLabel();
        raisonsocialeLabel = new javax.swing.JLabel();
        commentaire = new javax.swing.JTextField();
        nclientLabel = new javax.swing.JLabel();
        caffaireblLabel = new javax.swing.JLabel();
        caffairefactLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        modificationButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Clients = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clients");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identification des Clients", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        raisonsociale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                raisonsocialeKeyReleased(evt);
            }
        });

        commentaireLabel.setText("Commentaire:");

        nclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nclientKeyReleased(evt);
            }
        });

        telLabel.setText("Tèl:");

        newButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newButton.setText("Nouveau");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        emailLabel.setText("Email:");

        IFiscalLabel.setText("Ident. Fiscal:");

        narticleLabel.setText("Narticle :");

        dateRCLabel.setText("Date RC:");

        lieuRCLabel.setText("Lieu RC:");

        date_rc.setDateFormatString("dd.MM.yyyy");

        caffairefact.setEditable(false);
        caffairefact.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        caffairefact.setEnabled(false);

        caffairebl.setEditable(false);
        caffairebl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        caffairebl.setEnabled(false);
        caffairebl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffaireblActionPerformed(evt);
            }
        });

        nrcLabel.setText("N° RC:");

        contactPersonLabel.setText("Contact Person:");

        adresseLabel.setText("Adresse:");

        raisonsocialeLabel.setText("Raison Sociale:");

        nclientLabel.setText("Code Client :");

        caffaireblLabel.setText("Total Bl:");

        caffairefactLabel.setText("Total Fact   :");

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteButton.setText("Supprimer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modificationButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modificationButton.setText("Modification");
        modificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveButton.setText("Sauvegarder");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        btn_quitter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(commentaireLabel)
                                    .addGap(29, 29, 29))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(IFiscalLabel)
                                    .addGap(33, 33, 33)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nrc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(caffairebl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(176, 176, 176)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(caffairefactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                            .addComponent(narticleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(dateRCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(date_rc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(narticle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(caffairefact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(54, 54, 54)
                                    .addComponent(lieuRCLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(lieuRC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(newButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deleteButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modificationButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(contactPersonLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(contactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(telLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nrcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(caffaireblLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(emailLabel)
                            .addGap(23, 23, 23)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adresseLabel)
                            .addComponent(nclientLabel))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nclient, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(raisonsocialeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(raisonsociale))
                            .addComponent(adresse))))
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raisonsocialeLabel)
                            .addComponent(raisonsociale)
                            .addComponent(nclient)
                            .addComponent(nclientLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adresseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adresse))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactPersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactPerson)
                            .addComponent(emailLabel)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel)
                            .addComponent(telLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateRCLabel)
                                    .addComponent(nrc)
                                    .addComponent(nrcLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lieuRCLabel)
                                    .addComponent(lieuRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(date_rc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IFiscal)
                    .addComponent(narticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(narticleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IFiscalLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caffairebl)
                    .addComponent(caffaireblLabel)
                    .addComponent(caffairefact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caffairefactLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentaire)
                    .addComponent(commentaireLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(modificationButton)
                    .addComponent(deleteButton)
                    .addComponent(newButton)
                    .addComponent(btn_quitter))
                .addContainerGap())
        );

        Table_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ClientsMouseClicked(evt);
            }
        });
        Table_Clients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_ClientsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Clients);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
     try {                           
                nclient.setText("");                
                vider_champs();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }               
    }//GEN-LAST:event_newButtonActionPerformed

    private void vider_champs()
    {                          
                raisonsociale.setText("");
                adresse.setText("");                
                contactPerson.setText("");                
                tel.setText("");                
                email.setText("");                
                nrc.setText("");                                               
                date_rc.setDate(null);
                lieuRC.setText("");                
                IFiscal.setText("");                
                narticle.setText("");           
                caffairebl.setText("");
                caffairefact.setText("");
                caffairefact.setEditable(false);
                caffairebl.setEditable(false);                
                caffairefact.setEnabled(false);
                caffairebl.setEnabled(false);                
                commentaire.setText("");
    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
             
             double mnt = Double.parseDouble(caffairefact.getText().replaceAll(" ", "").replaceAll(",", "."))+Double.parseDouble(caffairebl.getText().replaceAll(" ", "").replaceAll(",", "."));
             if ( mnt > 0.00) {
                      // affiche_champs();     
                JOptionPane.showMessageDialog(null, " Client possède un Solde !");
                       } 
                       else {
                        String sql = "delete from client where nclient = '" + nclient.getText() + "'";
                        St.executeUpdate(sql);        
                        vider_champs();
                        Update_Table_Clients();
                       }
     } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

       }
       
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationButtonActionPerformed
         try {
            
            date_rc.setDateFormatString("yyyy-MM-dd");                         
            String query = "Update  client set raison_sociale = '"
            +raisonsociale.getText().replace( "'",  "\\'")+"', adresse ='"
            +adresse.getText().replace( "'",  "\\'")+"', contact_person ='"
            +contactPerson.getText().replace( "'",  "\\'")+"', nrc ='"
            //+0+"','"
            //+0+"','"
            +nrc.getText()+"', date_rc ='"
            +((JTextField)date_rc.getDateEditor().getUiComponent()).getText()+"', lieu_rc ='"
            +lieuRC.getText()+"', i_fiscal ='"
            +IFiscal.getText()+"', n_article ='"
            +narticle.getText()+"', tel ='"
            +tel.getText()+"', email='"        
            +email.getText()+"', commentaire ='"
            +commentaire.getText().replace( "'",  "\\'")+"' where nclient= '" + nclient.getText() + "'";         
            St.executeUpdate(query);
            Update_Table_Clients();
            JOptionPane.showMessageDialog(null,"Client modifié !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la modification de la table\n" + e.getMessage());

        }
         date_rc.setDateFormatString("dd-MM-yyyy");                         
         Update_Table_Clients();
    }//GEN-LAST:event_modificationButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    try {   
        
         String dt;
         date_rc.setDateFormatString("yyyy.MM.dd");
         dt=((JTextField)date_rc.getDateEditor().getUiComponent()).getText().trim();
         
        if (dt.length()==0){
        dt="1900.01.01";

         //JOptionPane.showMessageDialog(null,"Salam");
         //commentaire.setText(query);
        }
        // JOptionPane.showMessageDialog(null,dt.length());
        // JOptionPane.showMessageDialog(null,dt);
            
            String query = "insert into client values ('"
            +nclient.getText().replace( "'",  "\\'")+"','"
            +raisonsociale.getText().replace( "'",  "\\'") +"','"
            +adresse.getText().replace("'", "\\'")+"','"
            +contactPerson.getText().replace( "'",  "\\'")+"','"
            +0+"','"
            +0+"','"
            +nrc.getText()+"','"
            +dt+"','"
            +lieuRC.getText()+"','"
            +IFiscal.getText()+"','"
            +narticle.getText()+"','"
            +tel.getText()+"','"        
            +email.getText()+"','"
            +commentaire.getText().replace( "'",  "\\'")+"')";        
            
            //commentaire.setText(query);
            St.executeUpdate(query);
            Update_Table_Clients();
            JOptionPane.showMessageDialog(null,"Client ajouté !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
         date_rc.setDateFormatString("dd-MM-yyyy");                         
         Update_Table_Clients();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void caffaireblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffaireblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caffaireblActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String pilote = "com.mysql.jdbc.Driver";
        try {
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base+"?zeroDateTimeBehavior=convertToNull";    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        Update_Table_Clients();
    }//GEN-LAST:event_formWindowOpened

    private void Table_ClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClientsMouseClicked
      try {
            int row = Table_Clients.getSelectedRow();
            String Table_click = (Table_Clients.getModel().getValueAt(row, 0).toString());
            String sql = "select * from client where nclient = '" + Table_click + "'";

           // Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();
            Rs = St.executeQuery(sql);

            if (Rs.next()) {
                affiche_champs();                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }                     
    }//GEN-LAST:event_Table_ClientsMouseClicked

private void affiche_champs() {
               try {
                String add1 = Rs.getString("nclient");
                nclient.setText(add1);
                String add2 = Rs.getString("raison_sociale");
                raisonsociale.setText(add2);
                String add3 = Rs.getString("adresse");
                adresse.setText(add3);
                String add4 = Rs.getString("contact_person");
                contactPerson.setText(add4);
                String add5 = Rs.getString("tel");
                tel.setText(add5);
                String add6 = Rs.getString("email");
                email.setText(add6);
                String add7 = Rs.getString("nrc");
                nrc.setText(add7);
                Date add8 = Rs.getDate("date_rc");
                date_rc.setDate(add8);
                String add9 = Rs.getString("lieu_rc");
                lieuRC.setText(add9);
                String add10 = Rs.getString("i_fiscal");
                IFiscal.setText(add10);
                String add11 = Rs.getString("n_article");
                narticle.setText(add11);
                narticle.setText(add11);
                caffairefact.setEnabled(true);
                caffairebl.setEnabled(true);                                               
                //String add12 = Rs.getString("c_affaire_fact");
                String add12 = Rs.getString("c_affaire_fact");
                caffairefact.setText(mntFmt.mntFmt(Double.parseDouble(add12)));
                String add13 = Rs.getString("c_affaire_bl");
                caffairebl.setText(mntFmt.mntFmt(Double.parseDouble(add13)));
                String add14 = Rs.getString("commentaire");
                commentaire.setText(add14);
               } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
}

/*
private void affiche_champs_s_raison() {
               try {
                String add1 = Rs.getString("nclient");
                nclient.setText(add1);
                String add2 = Rs.getString("raison_sociale");
                raisonsociale.setText(add2);
                String add3 = Rs.getString("adresse");
                adresse.setText(add3);
                String add4 = Rs.getString("contact_person");
                contactPerson.setText(add4);
                String add5 = Rs.getString("tel");
                tel.setText(add5);
                String add6 = Rs.getString("email");
                email.setText(add6);
                String add7 = Rs.getString("nrc");
                nrc.setText(add7);
                Date add8 = Rs.getDate("date_rc");
                date_rc.setDate(add8);
                String add9 = Rs.getString("lieu_rc");
                lieuRC.setText(add9);
                String add10 = Rs.getString("i_fiscal");
                IFiscal.setText(add10);
                String add11 = Rs.getString("n_article");
                narticle.setText(add11);
                narticle.setText(add11);
                caffairefact.setEnabled(true);
                caffairebl.setEnabled(true);                                               
                //String add12 = Rs.getString("c_affaire_fact");
                Double add12 = Rs.getDouble("c_affaire_fact");
                caffairefact.setText(add12.toString());
                String add13 = Rs.getString("c_affaire_bl");
                caffairebl.setText(add13);
                String add14 = Rs.getString("commentaire");
                commentaire.setText(add14);
               } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
}

*/
    
    private void Table_ClientsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_ClientsKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
            try {
                int row = Table_Clients.getSelectedRow();
                String Table_click = (Table_Clients.getModel().getValueAt(row, 0).toString());
                String sql = "select * from client where nclient = '" + Table_click + "'";

               // Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
                //St = cnx.createStatement();
                Rs = St.executeQuery(sql);
                if (Rs.next()) {
                affiche_champs();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
     }   
    }//GEN-LAST:event_Table_ClientsKeyReleased

    private void nclientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nclientKeyReleased
        try {
             String sql = "select * from client where nclient = '" + nclient.getText() + "'";
             Rs = St.executeQuery(sql);        
                       if (Rs.next()) {
                       affiche_champs();     
                
                       } else {   
                        vider_champs();
                       }
} catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
        
        
    }//GEN-LAST:event_nclientKeyReleased

    private void raisonsocialeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_raisonsocialeKeyReleased
     /*try {
             String sql = "select * from client where raison_sociale = '" + raisonsociale.getText() + "'";
             Rs = St.executeQuery(sql);        
                       if (Rs.next()) {
                       affiche_champs_s_raison();                    
                       } else { 
                         nclient.setText("");
                         vider_champs();
                       }
} catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
        
       */ 
    }//GEN-LAST:event_raisonsocialeKeyReleased

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Clients( final String bas) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients(bas).setVisible(true);
            }
        });
    }
   // Déclaration des variables
    private Statement St;
    private ResultSet Rs;
    private Connection cnx;
    public String base;
    MyTableModel tm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IFiscal;
    private javax.swing.JLabel IFiscalLabel;
    private javax.swing.JTable Table_Clients;
    private javax.swing.JTextField adresse;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JTextField caffairebl;
    private javax.swing.JLabel caffaireblLabel;
    private javax.swing.JTextField caffairefact;
    private javax.swing.JLabel caffairefactLabel;
    private javax.swing.JTextField commentaire;
    private javax.swing.JLabel commentaireLabel;
    private javax.swing.JTextField contactPerson;
    private javax.swing.JLabel contactPersonLabel;
    private javax.swing.JLabel dateRCLabel;
    private com.toedter.calendar.JDateChooser date_rc;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lieuRC;
    private javax.swing.JLabel lieuRCLabel;
    private javax.swing.JButton modificationButton;
    private javax.swing.JTextField narticle;
    private javax.swing.JLabel narticleLabel;
    private javax.swing.JTextField nclient;
    private javax.swing.JLabel nclientLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nrc;
    private javax.swing.JLabel nrcLabel;
    private javax.swing.JTextField raisonsociale;
    private javax.swing.JLabel raisonsocialeLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tel;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables
}
