/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author IT
 */
public class entree_stock extends javax.swing.JFrame {

    /**
     * Creates new form entree_stock
     */
    public entree_stock(String par,String det, String mas, String bas) {
        //JOptionPane.showMessageDialog(null, parametre);
        parametre =par; 
        fichier_detail= det;
        fichier_master=mas;
        base=bas;
        
        initComponents();
            // 1. Get default keys
      Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
       ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nfact = new javax.swing.JTextField();
        txt_montant_tot_fact = new javax.swing.JTextField();
        txt_n_cheque = new javax.swing.JTextField();
        txt_banque = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        date_fact = new com.toedter.calendar.JDateChooser();
        txt_code_four = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        txt_stock_f = new javax.swing.JTextField();
        txt_stock_bl = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Factures = new javax.swing.JTable();
        txt_prix_unit = new javax.swing.JTextField();
        txt_code_art = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_timbre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_s_total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_qte = new javax.swing.JTextField();
        txt_prix_tot = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txt_total_tva = new javax.swing.JTextField();
        txt_tva = new javax.swing.JTextField();
        sauvegarder = new javax.swing.JButton();
        Enregistrer = new javax.swing.JButton();
        btn_rappeler = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txt_montant_tot_fact.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_montant_tot_fact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_montant_tot_factFocusLost(evt);
            }
        });

        jLabel1.setText("N°Facture ");

        jLabel2.setText("Date Facture");

        jLabel3.setText("Code fournisseur ");

        jLabel4.setText("Nom");

        jLabel5.setText("Montant Facture");

        jLabel6.setText("N°Cheque");

        jLabel7.setText("Banque ");

        txt_code_four.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_code_four.setVerifyInputWhenFocusTarget(false);
        txt_code_four.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_code_fourFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_code_fourFocusLost(evt);
            }
        });
        txt_code_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_code_fourActionPerformed(evt);
            }
        });
        txt_code_four.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_code_fourKeyReleased(evt);
            }
        });

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txt_stock_f.setEditable(false);
        txt_stock_f.setEnabled(false);

        txt_stock_bl.setEditable(false);
        txt_stock_bl.setEnabled(false);

        jLabel17.setText("Stock F");

        jLabel18.setText("Stock BL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nfact, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_montant_tot_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_n_cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_banque, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_code_four, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stock_f, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txt_stock_bl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txt_code_four, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_montant_tot_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_n_cheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_stock_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_stock_bl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        Table_Factures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Factures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_FacturesMouseClicked(evt);
            }
        });
        Table_Factures.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_FacturesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Factures);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        txt_prix_unit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_prix_unit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_prix_unitFocusGained(evt);
            }
        });
        txt_prix_unit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prix_unitKeyTyped(evt);
            }
        });

        txt_code_art.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_code_artCaretUpdate(evt);
            }
        });
        txt_code_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_code_artActionPerformed(evt);
            }
        });
        txt_code_art.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_code_artFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_code_artFocusLost(evt);
            }
        });
        txt_code_art.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_code_artKeyReleased(evt);
            }
        });

        jLabel15.setText("T.V.A");

        jLabel14.setText("Timbre ");

        jLabel10.setText("TVA");

        txt_timbre.setEditable(false);
        txt_timbre.setBackground(new java.awt.Color(255, 255, 255));
        txt_timbre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_timbre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_timbre.setEnabled(false);

        jLabel9.setText("Prix Unitaire");

        jLabel12.setText("Prix Total ");

        txt_s_total.setEditable(false);
        txt_s_total.setBackground(new java.awt.Color(255, 255, 255));
        txt_s_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_s_total.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_s_total.setEnabled(false);

        jLabel11.setText("Quantité");

        jLabel8.setText("Description");

        jLabel13.setText("Code Article");

        txt_qte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_qte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qteActionPerformed(evt);
            }
        });
        txt_qte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qteFocusLost(evt);
            }
        });
        txt_qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qteKeyTyped(evt);
            }
        });

        txt_prix_tot.setEditable(false);
        txt_prix_tot.setBackground(new java.awt.Color(255, 255, 255));
        txt_prix_tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_prix_tot.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_prix_tot.setEnabled(false);

        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel16.setText("S / Total");

        txt_total_tva.setEditable(false);
        txt_total_tva.setBackground(new java.awt.Color(255, 255, 255));
        txt_total_tva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_tva.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_total_tva.setEnabled(false);

        txt_tva.setEditable(false);
        txt_tva.setBackground(new java.awt.Color(255, 255, 255));
        txt_tva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tva.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_tva.setEnabled(false);

        sauvegarder.setText("Sauvegarder");
        sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderActionPerformed(evt);
            }
        });

        Enregistrer.setText("Ajouter ligne");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });

        btn_rappeler.setText("Rappeler");
        btn_rappeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rappelerActionPerformed(evt);
            }
        });

        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_code_art, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(475, 475, 475)
                                .addComponent(jLabel9)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tva, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txt_prix_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel12))
                                    .addComponent(txt_prix_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_total_tva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_timbre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_s_total, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Enregistrer)
                        .addGap(79, 79, 79)
                        .addComponent(sauvegarder)
                        .addGap(50, 50, 50)
                        .addComponent(btn_supprimer)
                        .addGap(44, 44, 44)
                        .addComponent(btn_rappeler)
                        .addGap(55, 55, 55)
                        .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1572, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_code_art, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_prix_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_prix_tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_s_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_timbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enregistrer)
                    .addComponent(sauvegarder)
                    .addComponent(btn_supprimer)
                    .addComponent(btn_rappeler)
                    .addComponent(btn_quitter))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_prix_unitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_unitKeyTyped
        char kar = evt.getKeyChar();

        if ( !(kar >='0' && kar <= '9')){

            if (!( kar ==',' | kar =='.')){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_prix_unitKeyTyped

private void mettre_jour_stock_debut(String xcode_art, String oper, String qte, String type_fact)
    {
    int x_resultat = 0;
     
       
    try {
      
       
        String sql= "select stock_f,stock_bl from article where narticle = '" + xcode_art + "'";    
        Rs = St.executeQuery(sql);
        
        if (Rs.next()) {
        
        String xstock_f = Rs.getString(type_fact);
        int v_xstock_f = Integer.parseInt(xstock_f);
        int xqte = Integer.parseInt(qte);
       if (!"ajouter1".equals(oper) ) {
        x_resultat = v_xstock_f+xqte;
       } else 
       {
        x_resultat = v_xstock_f-xqte;
        
       }      
        //String sql1 = "update article set stock_f = '"+n_xstock.toString()+"' where narticle = '" +xcode_art+"'";                                    
        String query = "update article set "+type_fact +" = '" +x_resultat +"' where narticle = '" +xcode_art+"'";                               
        JOptionPane.showMessageDialog(null, query);     
        St3.executeUpdate(query);
       }                
    }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "faute" + e.getMessage());    
    }
}

private void fillCombo1() {
    String sql ="select * from fournisseur order by nom_fournisseur";
    try {
    jComboBox1.addItem("          ");    
    Rs = St.executeQuery(sql);
    while (Rs.next() ) {
       String nme = Rs.getString("nom_fournisseur");
       String nme1 = Rs.getString("nfournisseur");
       jComboBox1.addItem(nme1+" "+nme);
    }
    
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la liste jComboBox1\n" + e.getMessage());
            }
    }
private void fillCombo2() {
    String sql ="select * from article order by designation";
    try {
    jComboBox2.addItem("          ");   
    
    Rs = St.executeQuery(sql);
    while (Rs.next() ) {
       String nme = Rs.getString("designation");
       //String nme1 = Rs.getString("narticle");
       jComboBox2.addItem(nme);
    }
    
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la liste jComboBox1\n" + e.getMessage());
            }
    }
    
    private void mettre_jour_stock( String xcode_art, String oper, String qte)
    {
        int x_resultat = 0;       
    try {
    
        String sql= "select stock_f,stock_bl from article where narticle = '" + xcode_art + "'";    
        Rs = St.executeQuery(sql);
        
        if (Rs.next()) {
        //String xstock_f = Rs.getString("stock_f");
        String xstock_f = Rs.getString(parametre);
        int v_xstock_f = Integer.parseInt(xstock_f);
        int xqte = Integer.parseInt(qte);
       if (!"ajouter1".equals(oper) ) {
        x_resultat = v_xstock_f+xqte;
       } else 
       {
        x_resultat = v_xstock_f-xqte;
        
       }
      
        //String sql1 = "update article set stock_f = '"+n_xstock.toString()+"' where narticle = '" +xcode_art+"'";                
          
          
          String query = "update article set "+parametre +" = '" +x_resultat +"' where narticle = '" +xcode_art+"'";                        
       
        JOptionPane.showMessageDialog(null, query);
     
        St3.executeUpdate(query);
       
       }        
        
    }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la mise à jour dans la table Article\n" + e.getMessage());
    
    }
    }
    private void calcul_des_montant() {
            
      try {       
      String sql ="select sum(qte*prix) as \"s_total\",sum(qte*prix*tva/100) as \"s_tva\" from facture_a" ;
        Rs = St.executeQuery(sql);
        if (Rs.next()) {
        String add1 = Rs.getString("s_total")+"0";
        String add2 = Rs.getString("s_tva")+"0";
        if ("null0".equals(add1)) {
        add1="0.0";
        add2="0.0";
        } else {
        add1 = Rs.getString("s_total");
        add2 = Rs.getString("s_tva");
        }        
        double add1_d = Double.parseDouble(add1);
        double add2_d = Double.parseDouble(add2);
        xtot_ht=add1_d;
        xtot_tva=add2_d;
        add1= mntFmt.mntFmt(add1_d);
        add2= mntFmt.mntFmt(add2_d);
        txt_s_total.setText(add1);
        txt_total_tva.setText(add2);
        timbre = add1_d*1/100;
        if (timbre > 2500.00) {
         timbre = 2500.00;
        }
        String add3 =mntFmt.mntFmt(timbre);
        txt_timbre.setText(add3);
        //txt_s_total.setEnabled(false);
        
        }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Erreur dans la somme" + e.getMessage());
             }
}
    private void champs_vide(){        
                txt_code_art.setText("");
                 
                jComboBox2.setSelectedIndex(0); 
                txt_prix_unit.setText("");
                txt_tva.setText("");                 
                txt_stock_f.setText("");                
                txt_stock_bl.setText("");
                txt_qte.setText("");
                txt_prix_tot.setText("");        
    }
    
    private void affiche_champs() {
               try {
               // String add1 = Rs.getString("nfact");
               // txt_nfact.setText(add1);
                //String add2 = Rs.getString("raison_sociale");
                //txt_raison_sociale.setText(add2);
                
                
                String add3 = Rs.getString("Code Article");
                txt_code_art.setText(add3);
                String add4 = Rs.getString("Designation");

                for (j=0 ; j < jComboBox2.getItemCount() ; j++) {
  
                    if (add4.equals(jComboBox2.getItemAt(j).toString())) {
                
                        break;  
                 }
                }
                jComboBox2.setSelectedIndex(j);                                                                                      
                String add5 = Rs.getString("Prix Unitaire");
                txt_prix_unit.setText(mntFmt.mntFmt(Double.parseDouble(add5)));
                String add6 = Rs.getString("TVA");
                txt_tva.setText(add6);
                String add7 = Rs.getString("Quantité");
                txt_qte.setText(add7);
                String add9 = Rs.getString("Prix Total");                
                txt_prix_tot.setText(mntFmt.mntFmt(Double.parseDouble(add9))); 
                //String txt_spell="";
                //String X=Numb_to_Spell.spell(Double.parseDouble(add9), txt_spell);
                //JOptionPane.showMessageDialog(null, X);
               } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
}
    
    
    private void txt_code_artCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_code_artCaretUpdate

    }//GEN-LAST:event_txt_code_artCaretUpdate

    private void txt_code_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_code_artActionPerformed

    }//GEN-LAST:event_txt_code_artActionPerformed

    private void txt_code_artFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_code_artFocusGained
        txt_code_art.setText("");
    }//GEN-LAST:event_txt_code_artFocusGained

    private void txt_code_artFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_code_artFocusLost
        txt_code_art.setInputVerifier(new Pass_Verifier_Art(base));
        String sql = "select * from article where narticle = '" + txt_code_art.getText() +"'";
        try {
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                String add = Rs.getString("designation");
                String add1 = Rs.getString("narticle");
                txt_code_art.setText(add1);

                for (j=0 ; j < jComboBox2.getItemCount() ; j++) {

                    if (add.equals(jComboBox2.getItemAt(j).toString())) {

                        break;
                    }
                }
                jComboBox2.setSelectedIndex(j);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }

    }//GEN-LAST:event_txt_code_artFocusLost

    private void txt_code_artKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_artKeyReleased
        try {
            String sql = "select * from article where narticle = '" + txt_code_art.getText() + "'";
            Rs = St.executeQuery(sql);

            if (Rs.next()) {
                //JOptionPane.showMessageDialog(null, "trouvé");
                String add4 = Rs.getString("Designation");

                for (j=0 ; j < jComboBox2.getItemCount() ; j++) {

                    if (add4.equals(jComboBox2.getItemAt(j).toString())) {

                        break;
                    }
                }
                jComboBox2.setSelectedIndex(j);
                String add5 = Rs.getString("Prix_unitaire");
                txt_prix_unit.setText(mntFmt.mntFmt(Double.parseDouble(add5)));
                String add6 = Rs.getString("TVA");
                txt_tva.setText(add6);
                String add7 = Rs.getString("stock_f");
                txt_stock_f.setText(add7);
                String add8 = Rs.getString("stock_bl");
                txt_stock_bl.setText(add8);
                txt_qte.setText("");
                txt_prix_tot.setText("");
            } else {
                jComboBox2.setSelectedIndex(0);
                txt_prix_unit.setText("");
                txt_tva.setText("");
                txt_stock_f.setText("");
                txt_stock_bl.setText("");
                txt_qte.setText("");
                txt_prix_tot.setText("");
                // JOptionPane.showMessageDialog(null, txt_code_art);
                //evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
    }//GEN-LAST:event_txt_code_artKeyReleased

    private void txt_qteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qteActionPerformed

        stot_ligne = Double.parseDouble(txt_prix_unit.getText())  * Double.parseDouble(txt_qte.getText());
        txt_prix_tot.setText(mntFmt.mntFmt(Double.parseDouble((stot_ligne.toString()))));

    }//GEN-LAST:event_txt_qteActionPerformed

    private void txt_qteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qteFocusLost

        if ("".equals(txt_prix_unit.getText() )){
            txt_prix_unit.setText("0");
        }
        if ("".equals(txt_tva.getText() )){
            txt_prix_unit.setText("0");
        }
        if ("".equals(txt_qte.getText())) {
            txt_qte.setText("0");
        }
        stot_ligne = Double.parseDouble(txt_prix_unit.getText().replaceAll(" ", "").replaceAll(",", "."))  * (Double.parseDouble(txt_qte.getText().replaceAll(" ", "").replaceAll(",", ".")));
        prix_unitaire=Double.parseDouble(txt_prix_unit.getText().replaceAll(" ", "").replaceAll(",", "."));
        txt_prix_tot.setText(mntFmt.mntFmt(Double.parseDouble((stot_ligne.toString()))));
        tva = stot_ligne*Double.parseDouble(txt_tva.getText().replaceAll(" ", "").replaceAll(",", "."))/100;
        txt_prix_unit.setText(mntFmt.mntFmt(Double.parseDouble((prix_unitaire.toString()))));

    }//GEN-LAST:event_txt_qteFocusLost

    private void txt_qteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qteKeyTyped
        char kar = evt.getKeyChar();

        if ( !(kar >='0' && kar <= '9')){

            if (!( kar ==',' | kar =='.')){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_qteKeyTyped

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible

        String tmp = (String)jComboBox2.getSelectedItem();
        String sql = "select * from article where designation = '" + tmp + "'";
        try {
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                String add = Rs.getString("narticle");
                txt_code_art.setText(add);
                String add5 = Rs.getString("Prix_unitaire");
                txt_prix_unit.setText(mntFmt.mntFmt(Double.parseDouble(add5)));
                String add6 = Rs.getString("TVA");
                txt_tva.setText(add6);
                String add7 = Rs.getString("stock_f");
                txt_stock_f.setText(add7);
                String add8 = Rs.getString("stock_bl");
                txt_stock_bl.setText(add8);
                txt_qte.setText("");
                txt_prix_tot.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Pas de article pour ce code" );
            }
        } catch (Exception e) { JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void Update_Table_Factures() {

        try {            
            String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_a AS F, article AS A where F.narticle=A.narticle order by F.id" ;                      
            tm = new MyTableModel(sql,base);
            Table_Factures.setModel(tm);
            Table_Factures.setDefaultRenderer(Double.class, new TKMntRenderer());
             } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table Clients\n" + e.getMessage());
        }
    }   
    
    private void sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderActionPerformed

        try {
          if ("".equals(txt_nfact.getText()) ) {
           JOptionPane.showMessageDialog(null, "Merci de Saisir le N°Facture !");
          }
          else {    
            String sql = "select id, Narticle , prix, tva, qte , total_ligne from facture_a where narticle='"+txt_code_art.getText()+"'";
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            St1 = cnx.createStatement();
            St3 = cnx.createStatement();
            St = cnx.createStatement();
            Rs = St.executeQuery(sql);
            if (Rs.next()) {

                String add7 = Rs.getString("qte");

                mettre_jour_stock(txt_code_art.getText() , "ajouter1", add7);
                String query = "update facture_a set qte ='"
                +txt_qte.getText() +"', prix ='"
                +prix_unitaire.toString()+"', total_ligne ='"
                +stot_ligne.toString()+"' where narticle = '" +txt_code_art.getText()+"'";
                St.executeUpdate(query);
                Update_Table_Factures();
                calcul_des_montant();
                mettre_jour_stock(txt_code_art.getText() , "restituer1", txt_qte.getText());
                JOptionPane.showMessageDialog(null,"ligne moodifiée !");

            }

            else {

                if (!"".equals(txt_code_art.getText()) ) {

                    String query = "insert into facture_a (nfact,narticle,nfournisseur, qte,tva,prix,total_ligne,type_fact) values ('"
                    +txt_nfact.getText()+"','"
                    +txt_code_art.getText()+"','"
                    +txt_code_four.getText()+"','"        
                    +txt_qte.getText()+"','"
                    +txt_tva.getText()+"','"
                    +prix_unitaire.toString()+"','"
                    +stot_ligne.toString()+"','"
                    +parametre+ "')";
                    St.executeUpdate(query);
                    Update_Table_Factures();
                    mettre_jour_stock(txt_code_art.getText() , "restituer1", txt_qte.getText());
                    int lastRow = Table_Factures.getRowCount() - 1;
                    Table_Factures.changeSelection(lastRow, lastRow, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
                }
            }
            calcul_des_montant();
            date_fact.setDateFormatString("yyyy-MM-dd");
            String query = "insert into "+fichier_master+ "(nfact,nfournisseur,date_fact,ncheque,banque,montant_ht,timbre,tva,autre_taxe) values ('"
            +txt_nfact.getText()+"','"
            +txt_code_four.getText()+"','"
            +((JTextField)date_fact.getDateEditor().getUiComponent()).getText()+"','"
            +txt_n_cheque.getText()+"','" 
            +txt_banque.getText()+"','"        
            +xtot_ht.toString()+"','"
            +timbre.toString()+"','"
            +xtot_tva.toString()+"','"
            +stot_ligne.toString()+"')";
            //JOptionPane.showMessageDialog(null,query);     
            St.executeUpdate(query);
            query ="insert into "+ fichier_detail+" (nfact, narticle,nfournisseur, qte,tva,prix,total_ligne) select nfact, narticle, nfournisseur, qte,tva,prix,total_ligne from facture_a";
            St.executeUpdate(query);
            Update_Table_Factures();
            query ="truncate table facture_a";
            St.execute(query);
            JOptionPane.showMessageDialog(null,"ligne ajoutée !");
            int r =JOptionPane.showConfirmDialog(null, "Voulez vous confirmer votre choix","Confirmation",JOptionPane.YES_NO_OPTION);

            if (r == 0) {
                JOptionPane.showMessageDialog(null,"Vous avez dit Yes !");
            }

            calcul_des_montant();
            }           
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
    }//GEN-LAST:event_sauvegarderActionPerformed

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
        try {
            //date_rc.setDateFormatString("yyyy-MM-dd");
            String sql = "select id, Narticle , prix, tva, qte , total_ligne from facture_a where narticle='"+txt_code_art.getText()+"'";
           // Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            St1 = cnx.createStatement();
            St3 = cnx.createStatement();
            St = cnx.createStatement();
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                String add7 = Rs.getString("qte");
                JOptionPane.showMessageDialog(null,add7);
                mettre_jour_stock(txt_code_art.getText() , "ajouter1", add7);
                String query = "update facture_a set qte ='"
                +txt_qte.getText() +"', prix ='"
                +prix_unitaire.toString()+"', total_ligne ='"
                +stot_ligne.toString()+"' where narticle = '" +txt_code_art.getText()+"'";
                St.executeUpdate(query);
                mettre_jour_stock(txt_code_art.getText() , "restituer1", txt_qte.getText());
                Update_Table_Factures();
                JOptionPane.showMessageDialog(null,"ligne moodifiée !");
            }

            else {
                String query = "insert into facture_a (nfact,narticle,nfournisseur, qte,tva,prix,total_ligne,type_fact) values ('"
                +txt_nfact.getText()+"','"
                +txt_code_art.getText()+"','"
                +txt_code_four.getText()+"','"
                +txt_qte.getText()+"','"
                +txt_tva.getText()+"','"
                +prix_unitaire.toString()+"','"
                +stot_ligne.toString()+"','"
                +parametre+ "')";
                St.executeUpdate(query);
                mettre_jour_stock(txt_code_art.getText() , "restituer1", txt_qte.getText());
                Update_Table_Factures();

                int lastRow = Table_Factures.getRowCount() - 1;
                //JOptionPane.showMessageDialog(null,lastRow);
                //Table_Factures.setRowSelectionInterval(lastRow, lastRow);
                Table_Factures.changeSelection(lastRow, lastRow, rootPaneCheckingEnabled, rootPaneCheckingEnabled);

                JOptionPane.showMessageDialog(null,"ligne ajoutée !");
            }
            calcul_des_montant();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());

        }
        //date_rc.setDateFormatString("dd-MM-yyyy");
        champs_vide();
        Update_Table_Factures();

    }//GEN-LAST:event_EnregistrerActionPerformed

    private void btn_rappelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rappelerActionPerformed
        // rappeler une facture_a si la table facture_a est vide.
        try {
            query="select count(*) as nbre_enr FROM facture_a";
            // JOptionPane.showMessageDialog(null,query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
                String add1 = Rs.getString("nbre_enr");
                JOptionPane.showMessageDialog(null,add1);
                if (Integer.parseInt(add1) > 0) {  JOptionPane.showMessageDialog(null, " Cette opération n'est pas autorisée à ce stade !" );
                }
                else {
                    query = "insert into facture_a (nfact, narticle,nfournisseur, qte,tva,prix,total_ligne)  select nfact, narticle,nfournisseur, qte,tva,prix,total_ligne from "+fichier_detail+" where nfact ='"+txt_nfact.getText()+"' and nfournisseur ='"+txt_code_four.getText()+"'" ;
                    //query ="insert into "+ fichier_detail+" (nfact, narticle, qte,tva,prix,total_ligne) select nfact, narticle, qte,tva,prix,total_ligne from facture";
                    JOptionPane.showMessageDialog(null,query);
                    St.executeUpdate(query);
                    affiche_champs();   
                    String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_a AS F, article AS A where F.narticle=A.narticle order by F.id" ;
                    tm = new MyTableModel(sql,base);
                    Table_Factures.setModel(tm);
                    Table_Factures.setDefaultRenderer(Double.class, new TKMntRenderer());

                }

            }
        } catch(Exception e) {  JOptionPane.showMessageDialog(null, "Erreur  \n" + e.getMessage());
        }

    }//GEN-LAST:event_btn_rappelerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed

        try {
            String sql ="delete from facture_a where narticle='"+txt_code_art.getText()+"'";
            int r =JOptionPane.showConfirmDialog(null, "Voulez vous confirmer la suppression ? ","Suppression",JOptionPane.YES_NO_OPTION);

            if (r == 0) {

                //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");

                St = cnx.createStatement();
                St.executeUpdate(sql);
                Update_Table_Factures();
                calcul_des_montant();
                JOptionPane.showMessageDialog(null," Ligne supprimée !");
                mettre_jour_stock(txt_code_art.getText() , "ajouter1", txt_qte.getText());
                champs_vide();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la suppresion table\n" + e.getMessage());

        }

    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void txt_code_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_code_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_code_fourActionPerformed

    private void txt_code_fourFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_code_fourFocusGained
        txt_code_four.setText("");
    }//GEN-LAST:event_txt_code_fourFocusGained

    private void txt_code_fourFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_code_fourFocusLost

        // JOptionPane.showMessageDialog(null, txt_code_cli.getText());
        txt_code_four.setInputVerifier(new Pass_Verifier_Fournisseur(base));
        String sql = "select * from fournisseur where nfournisseur = '" + txt_code_four.getText() +"'";
        try {
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                String add = txt_code_four.getText()+" " + Rs.getString("nom_fournisseur");
                String add1 = txt_code_four.getText();
                txt_code_four.setText(add1);

                for (j=0 ; j < jComboBox1.getItemCount() ; j++) {

                    if (add.equals(jComboBox1.getItemAt(j).toString())) {

                        break;
                    }
                }
                jComboBox1.setSelectedIndex(j);
            }   else {
                //JOptionPane.showMessageDialog(null, "Salam");
                //  txt_code_cli.setInputVerifier(new Pass_Verifier_Client());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());
        }
    }//GEN-LAST:event_txt_code_fourFocusLost

    private void txt_code_fourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_fourKeyReleased
        try {
            String sql = "select * from fournisseur where nfournisseur = '" + txt_code_four.getText() + "'";
            Rs = St.executeQuery(sql);

            if (Rs.next()) {
                //JOptionPane.showMessageDialog(null, "trouvé");
                String add4 = Rs.getString("nom_fournisseur");
                String add5 = txt_code_four.getText()+" "+add4;
                for (j=0 ; j < jComboBox1.getItemCount() ; j++) {

                    if (add5.equals(jComboBox1.getItemAt(j).toString())) {

                        break;
                    }
                }
                jComboBox1.setSelectedIndex(j);

            } else {
                // JOptionPane.showMessageDialog(null, txt_code_art);
                jComboBox1.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());
        }
    }//GEN-LAST:event_txt_code_fourKeyReleased

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        String tmp = (String)jComboBox1.getSelectedItem();
        String sql = "select * from fournisseur where nfournisseur+' '+nom_fournisseur = '" + tmp + "'";
        try {
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                String add = Rs.getString("nfournisseur");
                txt_code_four.setText(add);
            } else {
                JOptionPane.showMessageDialog(null, "Pas de fournisseur pour ce code" );
            }
        } catch (Exception e) { JOptionPane.showMessageDialog(null, "Erreur dans le comboBox \n" + e.getMessage());

    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        String pilote = "com.mysql.jdbc.Driver";
        
        try {
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }
            
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();
            query ="truncate table facture_a";
            St.execute(query);
  /*          query="select count(*) as nbre_enr FROM "+fichier_master+";";
            St.execute(query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add1 = Rs.getString("nbre_enr");
            if (Integer.parseInt(add1) > 0) {
            query="select max(nfact) as nfact_max FROM "+fichier_master+";";
            // JOptionPane.showMessageDialog(null, query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add2 = Rs.getString("nfact_max");
           // JOptionPane.showMessageDialog(null, add1);
            int_nfact= Integer.parseInt(add2)+1;
            } 
            }else {
            int_nfact=1;
             }            
            txt_nfact.setText(Integer.toString(int_nfact));
            //JOptionPane.showMessageDialog(null, txt_nfact.getText());
            
            }
*/
            fillCombo1();
            fillCombo2();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        Update_Table_Factures();    
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void Table_FacturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_FacturesMouseClicked
                try {
            int row = Table_Factures.getSelectedRow();                       
            String Table_click = (Table_Factures.getModel().getValueAt(row, 0).toString());                     
            String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_a AS F, article AS A where F.narticle=A.narticle and F.id ='"+ Table_click + "'";
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                affiche_champs();                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }

        
    }//GEN-LAST:event_Table_FacturesMouseClicked

    private void Table_FacturesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_FacturesKeyReleased
                if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
            try {
                int row = Table_Factures.getSelectedRow();
                String Table_click = (Table_Factures.getModel().getValueAt(row, 0).toString());
                String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture AS F, article AS A where F.narticle=A.narticle and F.id ='"+ Table_click + "'";
                
               // Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
               // St = cnx.createStatement();
                Rs = St.executeQuery(sql);
                if (Rs.next()) {
                affiche_champs();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
     }   
        
        
    }//GEN-LAST:event_Table_FacturesKeyReleased

    private void txt_montant_tot_factFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_montant_tot_factFocusLost
       //String txt_int =txt_montant_tot_fact.getText();
       txt_montant_tot_fact.setText(mntFmt.mntFmt(Double.parseDouble((txt_montant_tot_fact.getText()))));
       
    }//GEN-LAST:event_txt_montant_tot_factFocusLost

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void txt_prix_unitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_unitFocusGained
    txt_prix_unit.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prix_unitFocusGained
    
    /**
     * @param args the command line arguments
     */
    
    public static void entree_stock(final String par, final String det, final String mas, final String bas) {
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entree_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entree_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entree_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entree_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entree_stock(par,det,mas,bas).setVisible(true);
            }
        });
    }
    private Statement St,St1,St3;
    private ResultSet Rs,Rs1;
    private Connection cnx;
    public String parametre, fichier_detail, fichier_master, base;
    String query;
    
    int j, int_nfact;
    MyTableModel tm;
    Double stot_ligne =0.00, prix_unitaire=0.00, add1_d=.00, timbre = 0.00, tva = 0.00, xtot_ht=0.00, xtot_tva=0.00;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enregistrer;
    private javax.swing.JTable Table_Factures;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_rappeler;
    private javax.swing.JButton btn_supprimer;
    private com.toedter.calendar.JDateChooser date_fact;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sauvegarder;
    private javax.swing.JTextField txt_banque;
    private javax.swing.JTextField txt_code_art;
    private javax.swing.JTextField txt_code_four;
    private javax.swing.JTextField txt_montant_tot_fact;
    private javax.swing.JTextField txt_n_cheque;
    private javax.swing.JTextField txt_nfact;
    private javax.swing.JTextField txt_prix_tot;
    private javax.swing.JTextField txt_prix_unit;
    private javax.swing.JTextField txt_qte;
    private javax.swing.JTextField txt_s_total;
    private javax.swing.JTextField txt_stock_bl;
    private javax.swing.JTextField txt_stock_f;
    private javax.swing.JTextField txt_timbre;
    private javax.swing.JTextField txt_total_tva;
    private javax.swing.JTextField txt_tva;
    // End of variables declaration//GEN-END:variables
}
