/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

/**
 *
 * @author habib.belkacemi
 * 
 */

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class Fournisseur extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    public Fournisseur( String bas) {
        base = bas;
        initComponents();
        // 1. Get default keys
      Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);
        
    }
private void Update_Table_Fournisseur() {

        try {
            String sql = "select Nfournisseur as \"Code Fourni.\", Nom_Fournisseur as \"Nom\",Resp_fournisseur as \"Responsable\", adresse_fourni as \"Adresse\", Tel as \"Tél \", email as \"Email\", tel1 as \"Portable 1 \", tel2 as \"Portable2 \", caf as \"C.A.F\", cabl as \"C.A.BL\", commentaire as \"Commentaire\"  from fournisseur order by nom_fournisseur";
           // Rs = St.executeQuery(sql);
           // Table_Fournisseur.setModel(DbUtils.resultSetToTableModel(Rs));
            tm = new MyTableModel(sql, base);
            Table_Fournisseur.setModel(tm);
            Table_Fournisseur.setDefaultRenderer(Double.class, new TKMntRenderer());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table fournisseurs\n" + e.getMessage());

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Fournisseur = new javax.swing.JTable();
        code_fourn = new javax.swing.JLabel();
        nom_fourn = new javax.swing.JLabel();
        resp_fourn = new javax.swing.JLabel();
        adr_fourn = new javax.swing.JLabel();
        ntel = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        CAF = new javax.swing.JLabel();
        CABL = new javax.swing.JLabel();
        txt_code_fourn = new javax.swing.JTextField();
        txt_nom_fourn = new javax.swing.JTextField();
        txt_resp_fourn = new javax.swing.JTextField();
        txt_adr_fourn = new javax.swing.JTextField();
        txt_ntel = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_caf = new javax.swing.JTextField();
        txt_cabl = new javax.swing.JTextField();
        Ntel_port_1 = new javax.swing.JLabel();
        txt_port1 = new javax.swing.JTextField();
        Ntel_port_2 = new javax.swing.JLabel();
        txt_port2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_commentaire = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_ajouter = new javax.swing.JButton();
        btn_rechercher = new javax.swing.JButton();
        btn_nouveau = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fournisseur");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        Table_Fournisseur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Fournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_FournisseurMouseClicked(evt);
            }
        });
        Table_Fournisseur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_FournisseurKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Fournisseur);

        code_fourn.setText("Code Fournisseur  :");

        nom_fourn.setText("Nom  :");

        resp_fourn.setText("Responsable          :");

        adr_fourn.setText("Adresse                  :");

        ntel.setText("N° Téléphone         :");

        email.setText("Email   :");

        CAF.setText("C.A.F                     :");

        CABL.setText("C.A.BL :");

        txt_code_fourn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_code_fournKeyReleased(evt);
            }
        });

        txt_caf.setEditable(false);
        txt_caf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_cabl.setEditable(false);
        txt_cabl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Ntel_port_1.setText("N° Tél Portale 1      :");

        Ntel_port_2.setText("N° Tél Portale 2     :");

        jLabel1.setText("Commentaire          :");

        txt_commentaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_commentaireActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        btn_ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ajouter.setText("Enregistrer");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_rechercher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_rechercher.setText("Rechercher");
        btn_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercherActionPerformed(evt);
            }
        });

        btn_nouveau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nouveau.setText("Nouveau");
        btn_nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nouveauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btn_nouveau)
                .addGap(18, 18, 18)
                .addComponent(btn_ajouter)
                .addGap(18, 18, 18)
                .addComponent(btn_modifier)
                .addGap(31, 31, 31)
                .addComponent(btn_rechercher)
                .addGap(18, 18, 18)
                .addComponent(btn_supprimer)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modifier)
                    .addComponent(btn_supprimer)
                    .addComponent(btn_rechercher)
                    .addComponent(btn_ajouter)
                    .addComponent(btn_nouveau))
                .addContainerGap())
        );

        btn_quitter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resp_fourn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(code_fourn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ntel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adr_fourn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CAF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ntel_port_1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_commentaire)
                        .addGap(249, 249, 249))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_port1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_resp_fourn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ntel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(477, 477, 477))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txt_code_fourn)
                                        .addGap(327, 327, 327))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txt_adr_fourn, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Ntel_port_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_caf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CABL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_port2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cabl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(417, 417, 417))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(794, 794, 794)
                                .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nom_fourn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nom_fourn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(442, 442, 442))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code_fourn)
                    .addComponent(txt_code_fourn)
                    .addComponent(nom_fourn)
                    .addComponent(txt_nom_fourn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resp_fourn)
                    .addComponent(txt_resp_fourn))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_adr_fourn)
                    .addComponent(adr_fourn)
                    .addComponent(email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntel)
                    .addComponent(txt_ntel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ntel_port_1)
                    .addComponent(txt_port1)
                    .addComponent(Ntel_port_2)
                    .addComponent(txt_port2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CAF)
                    .addComponent(txt_caf)
                    .addComponent(CABL)
                    .addComponent(txt_cabl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quitter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String pilote = "com.mysql.jdbc.Driver";


        try {
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            St = cnx.createStatement();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        Update_Table_Fournisseur();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_commentaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_commentaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_commentaireActionPerformed

    private void Table_FournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_FournisseurMouseClicked
try {
            int row = Table_Fournisseur.getSelectedRow();
            String Table_click = (Table_Fournisseur.getModel().getValueAt(row, 0).toString());
            String sql = "select * from fournisseur where nfournisseur = '" + Table_click + "'";

            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();
            Rs = St.executeQuery(sql);

            if (Rs.next()) {
                Afficher();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
                     
        
        
    }//GEN-LAST:event_Table_FournisseurMouseClicked
 
    private void Afficher() 
    {
        try {
                String add1 = Rs.getString("nfournisseur");
                txt_code_fourn.setText(add1);
                String add2 = Rs.getString("nom_fournisseur");
                txt_nom_fourn.setText(add2);
                String add3 = Rs.getString("resp_fournisseur");
                txt_resp_fourn.setText(add3);
                String add4 = Rs.getString("adresse_fourni");
                txt_adr_fourn.setText(add4);
                String add5 = Rs.getString("tel");
                txt_ntel.setText(add5);
                String add6 = Rs.getString("email");
                txt_email.setText(add6);
                String add7 = Rs.getString("tel1");
                txt_port1.setText(add7);
                String add8 = Rs.getString("tel2");
                txt_port2.setText(add8);
                String add9 = Rs.getString("caf");
                txt_caf.setText(mntFmt.mntFmt(Double.parseDouble(add9)));
                String add10 = Rs.getString("cabl");
                txt_cabl.setText(mntFmt.mntFmt(Double.parseDouble(add10)));
                String add11 = Rs.getString("commentaire");
                txt_commentaire.setText(add11);
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
    }
    
    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        
      try {        
                    
          String query = "insert into fournisseur values ('"
                 +txt_code_fourn.getText().replace( "'",  "\\'")+"','"
                 +txt_nom_fourn.getText().replace( "'",  "\\'")+"','"
                 +txt_resp_fourn.getText().replace( "'",  "\\'")+"','"
                 +txt_adr_fourn.getText().replace( "'",  "\\'")+"','"
                 +txt_ntel.getText()+"','"
                 +txt_port1.getText()+"','"
                 +txt_port2.getText()+"','"
                 +0+"','"
                 +0+"','"
                 +txt_email.getText()+"','"
                 +txt_commentaire.getText().replace( "'",  "\\'")+"')";
                 
         
          St.executeUpdate(query);
          Update_Table_Fournisseur();
          JOptionPane.showMessageDialog(null,"Fournisseur ajouté !");  
            
          } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());
            
      }  
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        
    }//GEN-LAST:event_formKeyReleased

    private void Table_FournisseurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_FournisseurKeyReleased

          if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
            try {
                int row = Table_Fournisseur.getSelectedRow();
                String Table_click = (Table_Fournisseur.getModel().getValueAt(row, 0).toString());
                String sql = "select * from fournisseur where nfournisseur = '" + Table_click + "'";

             //   Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
               // St = cnx.createStatement();
                Rs = St.executeQuery(sql);

                if (Rs.next()) {

            
                String add1 = Rs.getString("nfournisseur");
                txt_code_fourn.setText(add1);
                String add2 = Rs.getString("nom_fournisseur");
                txt_nom_fourn.setText(add2);
                String add3 = Rs.getString("resp_fournisseur");
                txt_resp_fourn.setText(add3);
                String add4 = Rs.getString("adresse_fourni");
                txt_adr_fourn.setText(add4);
                String add5 = Rs.getString("tel");
                txt_ntel.setText(add5);
                String add6 = Rs.getString("email");
                txt_email.setText(add6);
                String add7 = Rs.getString("tel1");
                txt_port1.setText(add7);
                String add8 = Rs.getString("tel2");
                txt_port2.setText(add8);
                String add9 = Rs.getString("caf");
                txt_caf.setText(mntFmt.mntFmt(Double.parseDouble(add9)));
                String add10 = Rs.getString("cabl");
                txt_cabl.setText(mntFmt.mntFmt(Double.parseDouble(add10)));                
                String add11 = Rs.getString("commentaire");
                txt_commentaire.setText(add11);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }
}

// TODO add your handling code here:
    }//GEN-LAST:event_Table_FournisseurKeyReleased

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
      try {
      String query = "Update  fournisseur set nom_fournisseur = '"
                 +txt_nom_fourn.getText().replace( "'",  "\\'")+"',resp_fournisseur='"
                 +txt_resp_fourn.getText().replace( "'",  "\\'")+"',adresse_fourni='"
                 +txt_adr_fourn.getText().replace( "'",  "\\'")+"',tel='"
                 +txt_ntel.getText()+"',tel1='"
                 +txt_port1.getText()+"',tel2='"
                 +txt_port2.getText()+"',email='"
                // +0+"','"
                // +0+"',email'"
                 +txt_email.getText()+"',commentaire='"
                 +txt_commentaire.getText().replace( "'",  "\\'")+"' where nfournisseur= '" + txt_code_fourn.getText() + "'";  
              St.executeUpdate(query);
              Update_Table_Fournisseur();
      }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la modification de la table\n" + e.getMessage());

        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
      this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void btn_nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nouveauActionPerformed
        txt_code_fourn.setText("");       
        effacer_champ();                
    }//GEN-LAST:event_btn_nouveauActionPerformed

    private void effacer_champ()
            
    {
               // txt_code_fourn.setText("");
                txt_nom_fourn.setText("");
                txt_resp_fourn.setText("");                
                txt_adr_fourn.setText("");                
                txt_ntel.setText("");                
                txt_email.setText("");                
                txt_port1.setText("");                
                txt_port2.setText("");                
                txt_caf.setText(mntFmt.mntFmt(Double.parseDouble("0")));                
                txt_cabl.setText(mntFmt.mntFmt(Double.parseDouble("0")));                
                txt_commentaire.setText("");
    }
    private void btn_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercherActionPerformed
        try{
        String sql = "select * from fournisseur where nfournisseur = '" + txt_code_fourn.getText() + "'";
        Rs = St.executeQuery(sql);
       if (Rs.next()) {
        Afficher();
       }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la recherche \n" + e.getMessage());

        }
    }//GEN-LAST:event_btn_rechercherActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
       try{
        String sql = "delete from fournisseur where nfournisseur = '" + txt_code_fourn.getText() + "'";
       
       if (JOptionPane.showConfirmDialog(null,"Confimer la suppression", " Effacer", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION )  {
            St.executeUpdate(sql);
            Update_Table_Fournisseur();    
            effacer_champ();
        }

        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la recherche \n" + e.getMessage());

        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void txt_code_fournKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_fournKeyReleased
        try {
             String sql = "select * from fournisseur where nfournisseur  = '" + txt_code_fourn.getText() + "'";
             Rs = St.executeQuery(sql);        
                       if (Rs.next()) {
                       Afficher();     
                
                       } else {   
                        effacer_champ();
                       }
} catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());

        }
    }//GEN-LAST:event_txt_code_fournKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void Fournisseur(final String bas) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournisseur(bas).setVisible(true);
            }
        });
    }
// Déclaration des variables
    private Statement St;
    private ResultSet Rs;
    private Connection cnx;
    public String base;
    private int i;
    MyTableModel tm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CABL;
    private javax.swing.JLabel CAF;
    private javax.swing.JLabel Ntel_port_1;
    private javax.swing.JLabel Ntel_port_2;
    private javax.swing.JTable Table_Fournisseur;
    private javax.swing.JLabel adr_fourn;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_nouveau;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_rechercher;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel code_fourn;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nom_fourn;
    private javax.swing.JLabel ntel;
    private javax.swing.JLabel resp_fourn;
    private javax.swing.JTextField txt_adr_fourn;
    private javax.swing.JTextField txt_cabl;
    private javax.swing.JTextField txt_caf;
    private javax.swing.JTextField txt_code_fourn;
    private javax.swing.JTextField txt_commentaire;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nom_fourn;
    private javax.swing.JTextField txt_ntel;
    private javax.swing.JTextField txt_port1;
    private javax.swing.JTextField txt_port2;
    private javax.swing.JTextField txt_resp_fourn;
    // End of variables declaration//GEN-END:variables
}
