/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.design.JasperDesign;

/**
 *
 * @author IT
 */

public class list_banq extends javax.swing.JFrame {

    public list_banq(String par, String det, String mas, String bas) {
        //JOptionPane.showMessageDialog(null, parametre);        
        parametre = par;        
        fichier_detail = det;
        fichier_master = mas;
        base = bas;
    /**
     * Creates new form list_banq
     */
    //public list_banq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Banq = new javax.swing.JTable();
        txt_titre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_banque = new javax.swing.JTextField();
        btn_selectioner = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_modifier = new javax.swing.JButton();
        txt_nfact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tot_fact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_raison_sociale = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_bnq_dest = new javax.swing.JTextField();
        txt_ncheque = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        date_debut = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        date_fin = new com.toedter.calendar.JDateChooser();
        btn_valider = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_tot_esp = new javax.swing.JTextField();
        txt_tot_banq = new javax.swing.JTextField();
        txt_tot_term = new javax.swing.JTextField();
        txt_tot_table = new javax.swing.JTextField();
        txt_tot_marge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_recette_jour = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des Ventes");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Table_Banq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Banq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_BanqMouseClicked(evt);
            }
        });
        Table_Banq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_BanqKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Banq);

        txt_titre.setEditable(false);
        txt_titre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_titre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Banque :");

        btn_selectioner.setText("Sélectionner");
        btn_selectioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectionerActionPerformed(evt);
            }
        });
        btn_selectioner.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_selectionerFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txt_banque, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_selectioner)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btn_selectioner)
                    .addComponent(txt_banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        txt_nfact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nfactKeyReleased(evt);
            }
        });

        jLabel2.setText("N° Facture:");

        txt_tot_fact.setEditable(false);
        txt_tot_fact.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Montant");

        jLabel4.setText("Client :");

        txt_raison_sociale.setEditable(false);
        txt_raison_sociale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_raison_socialeActionPerformed(evt);
            }
        });

        jLabel5.setText("Banque à utiliser : ");

        jLabel6.setText("N°chèque:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_tot_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txt_bnq_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ncheque, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_nfact, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_raison_sociale, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_modifier)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_raison_sociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tot_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bnq_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_ncheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_modifier)
                .addGap(15, 15, 15))
        );

        jLabel7.setText("Période du :");

        jLabel8.setText("Au :");

        date_fin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_finFocusLost(evt);
            }
        });

        btn_valider.setText("Valider");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_fin, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(date_debut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(btn_valider)
                .addGap(122, 122, 122))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_valider))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jLabel9.setText("Espèce :");

        jLabel10.setText("Banque :");

        jLabel11.setText("Term     :");

        jLabel12.setText("Total     :");

        txt_tot_esp.setEditable(false);
        txt_tot_esp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_tot_esp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_esp.setEnabled(false);

        txt_tot_banq.setEditable(false);
        txt_tot_banq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_tot_banq.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_banq.setEnabled(false);

        txt_tot_term.setEditable(false);
        txt_tot_term.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_tot_term.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_term.setEnabled(false);

        txt_tot_table.setEditable(false);
        txt_tot_table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_tot_table.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_table.setEnabled(false);

        txt_tot_marge.setEditable(false);
        txt_tot_marge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_tot_marge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_marge.setEnabled(false);

        jLabel13.setText("Marge   :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txt_tot_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_tot_banq, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(txt_tot_term)
                                .addComponent(txt_tot_table))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tot_marge, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tot_esp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tot_banq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tot_term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tot_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tot_marge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(5, 5, 5))
        );

        btn_recette_jour.setText("Recette du jour");
        btn_recette_jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recette_jourActionPerformed(evt);
            }
        });

        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_quitter)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(326, 326, 326))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_recette_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(txt_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btn_recette_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_quitter)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
             String pilote = "com.mysql.jdbc.Driver";
             jPanel1.setVisible(false);
             jPanel2.setVisible(false);
             jPanel3.setVisible(false);
             jPanel4.setVisible(false);
             jPanel5.setVisible(false);
     //parametre ="banque";
        String titre="";
        query1="";
        list ="select NFact, f.Nclient, c.raison_sociale, date_fact,montant_ht, timbre, TVA,montant_ht+timbre+TVA, marge, banq, ncheque, nbc, nom_preneur,'F' from fact f, client c where f.nclient=c.nclient and banq " ;
            switch (parametre) {
                case "banque":
                    jPanel1.setVisible(true);
                    titre = "BANQUE";
                    condition=" not in('TERM','') order by banq" ;
                    query2= list+" "+ condition;
                    break;
                case "TERM" :   
                    titre = "TERM";
                    condition="  ='TERM'" ;
                    jPanel2.setVisible(true);
                    break;
                case "Espece" :   
                    titre = "ESPECE";
                 condition=" =''";
                    break;
                    
                case "periode" :   
                    titre = "Période";
                 condition=" <> 'y' order by banq ";
                 query1 ="select NFact, f.Nclient, c.raison_sociale, date_fact,montant_ht, timbre, TVA,montant_ht+timbre+TVA, marge, banq, ncheque, nbc, nom_preneur,'BL' from bl f, client c where f.nclient=c.nclient";
                 jPanel3.setVisible(true);
                 jPanel4.setVisible(true);
                 jPanel5.setVisible(true);
                    break;                                        
            }
            query= list+" "+ condition;                
            txt_titre.setText(titre);
            txt_titre.setBackground(Color.BLUE);
            txt_titre.setForeground(Color.WHITE);
            
        try {
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }
            sql = "truncate table fact_tmp";
            St.execute(sql);
            sql="insert into fact_tmp " + query;
            St.execute(sql);
           if (!query1.equals("")) {             
            sql="insert into fact_tmp " + query1;
            St.execute(sql);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        query = "select * from fact_tmp";
        Update_Table_Banq();       
    }//GEN-LAST:event_formWindowOpened

    private void btn_selectionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectionerActionPerformed
    selectionner();        
    }//GEN-LAST:event_btn_selectionerActionPerformed

    private void btn_selectionerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_selectionerFocusLost
      selectionner();
    }//GEN-LAST:event_btn_selectionerFocusLost

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        try
            {
            
          if ( txt_nfact.getText().equals(""))   {
             JOptionPane.showMessageDialog(null, "N°Facture vide !");
          }else {
              
           query =" select * from fact_tmp where nfact ='" + txt_nfact.getText() + "'";
           
           
           Rs = St.executeQuery(query);                        
           if (Rs.next()) {
           String sql_up="update fact set banq ='" 
                   +txt_bnq_dest.getText() +"', ncheque = '"
                   +txt_ncheque.getText() + "' where nfact = '" + txt_nfact.getText() + "'";
          
           St.executeUpdate(sql_up);
           sql_up ="delete from fact_tmp where nfact ='" + txt_nfact.getText() + "'";
           St.executeUpdate(sql_up);
           } else {
            JOptionPane.showMessageDialog(null, "Facture n'existe pas!" );
           }
           
           }
           Update_Table_Banq();       
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la recherche\n" + e.getMessage());
        }  
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void txt_raison_socialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_raison_socialeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_raison_socialeActionPerformed

    private void txt_nfactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nfactKeyReleased
     
        try {
            //select f.Nclient, c.raison_sociale,montant_ht, timbre, TVA, autre_taxe, banq, ncheque from fact f, client c where f.nclient=c.nclient  " ;
        query =" SELECT nfact, f.Nclient, c.raison_sociale as raison_sociale, montant_ht+timbre+ TVA as tot_fact, marge, banq, ncheque from fact_tmp f, client c where f.nclient=c.nclient and nfact LIKE '" + txt_nfact.getText() + "%'";
       // JOptionPane.showMessageDialog(null, query);
           
           Rs = St.executeQuery(query);                        
           if (Rs.next()) {               ;
                affiche_enr();
           } else {
                txt_tot_fact.setText(mntFmt.mntFmt(Double.parseDouble("0.00")));                
                txt_raison_sociale.setText("");
                txt_bnq_dest.setText("");                
                txt_ncheque.setText("");
            //JOptionPane.showMessageDialog(null, "Facture n'existe pas!" );
           }   
           Update_Table_Banq();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la recherche\n" + e.getMessage());
        }
    }//GEN-LAST:event_txt_nfactKeyReleased
private void affiche_enr() {
 try {
                
                String add5 = Rs.getString("tot_fact");
                txt_tot_fact.setText(mntFmt.mntFmt(Double.parseDouble(add5)));                
                String add6 = Rs.getString("raison_sociale");
                txt_raison_sociale.setText(add6);
                String add7 = Rs.getString("banq");
                txt_bnq_dest.setText(add7);
                String add8 = Rs.getString("ncheque");
                txt_ncheque.setText(add8);                
}catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la recherche\n" + e.getMessage());
        }
                
}
    
    private void Table_BanqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_BanqMouseClicked
        
        
        try {
            int row = Table_Banq.getSelectedRow();
            String Table_click = (Table_Banq.getModel().getValueAt(row, 0).toString());            
           query=  " SELECT nfact, f.Nclient, c.raison_sociale as raison_sociale, montant_ht+timbre+ TVA as tot_fact, marge, banq, ncheque from fact_tmp f, client c where f.nclient=c.nclient and nfact = '"+ Table_click + "'";
           //JOptionPane.showMessageDialog(null, query);
           Rs = St.executeQuery(query);
           if (Rs.next()) {
               String add4 = Rs.getString("nfact");
                txt_nfact.setText(add4);
            affiche_enr();
           }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
                 
    }//GEN-LAST:event_Table_BanqMouseClicked

    private void Table_BanqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_BanqKeyReleased
       
        try {
            int row = Table_Banq.getSelectedRow();
            String Table_click = (Table_Banq.getModel().getValueAt(row, 0).toString());            
           query=  " SELECT nfact, f.Nclient, c.raison_sociale as raison_sociale, montant_ht+timbre+ TVA as tot_fact, marge, banq, ncheque from fact_tmp f, client c where f.nclient=c.nclient and nfact = '"+ Table_click + "'";
           //JOptionPane.showMessageDialog(null, query);
           Rs = St.executeQuery(query);
           if (Rs.next()) {
                String add4 = Rs.getString("nfact");
                txt_nfact.setText(add4);
               affiche_enr();
           }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
        
    }//GEN-LAST:event_Table_BanqKeyReleased

    private void date_finFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_finFocusLost
        query ="select from fact where date_fact >= "+((JTextField) date_debut.getDateEditor().getUiComponent()).getText()+" and date_fact <= "+ ((JTextField) date_fin.getDateEditor().getUiComponent()).getText() ;
       // JOptionPane.showMessageDialog(null, query);
        Update_Table_Banq();
    }//GEN-LAST:event_date_finFocusLost

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
         
            //JOptionPane.showMessageDialog(null, date_debut);
        SimpleDateFormat lol = new SimpleDateFormat("yyyy-MM-dd");
            
          
            Date dt_deb1 = date_debut.getDate();
            Date dt_fin1 = date_fin.getDate();
  
           String dt1= lol.format(dt_deb1);
           String dt2= lol.format(dt_fin1);
      
        query ="select NFact, f.Nclient, c.raison_sociale, date_fact,montant_ht, timbre, TVA, montant_ht + timbre + tva, marge, banq, ncheque, nbc, nom_preneur,'F' from fact f, client c where f.nclient=c.nclient and  date_fact >= '"+dt1+"' and date_fact <= '"+dt2+"'";
        query1 ="select NFact, f.Nclient, c.raison_sociale, date_fact,montant_ht, timbre, TVA, montant_ht + timbre + tva,  marge, banq, ncheque, nbc, nom_preneur,'BL' from bl f, client c where f.nclient=c.nclient and  date_fact >= '"+dt1+"' and date_fact <= '"+dt2+"'";
         String sql = "truncate table fact_tmp";
        try {
            St.execute(sql);
                sql="insert into fact_tmp " + query;      
                //JOptionPane.showMessageDialog(null,sql);
                St.execute(sql);               
                sql="insert into fact_tmp " + query1;
                //JOptionPane.showMessageDialog(null,sql);
                St.execute(sql);
               
        } catch (SQLException ex) {
            Logger.getLogger(list_banq.class.getName()).log(Level.SEVERE, null, ex);
        }
        query="select * from fact_tmp";
        Update_Table_Banq();
        //calcul_recette();
    }//GEN-LAST:event_btn_validerActionPerformed

    private void btn_recette_jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recette_jourActionPerformed
       
       Date dt = new Date();
       SimpleDateFormat lol = new SimpleDateFormat("yyyy-MM-dd");
       String date_jour = lol.format(dt);    
       query ="select NFact, f.Nclient, c.raison_sociale, date_fact,montant_ht, timbre, TVA,montant_ht+timbre+TVA, marge, banq, ncheque, nbc, nom_preneur,'F' from fact f, client c where f.nclient=c.nclient and date_fact = '"+date_jour+"'";
       query1 ="select NFact, f.Nclient, c.raison_sociale, date_fact,montant_ht, timbre, TVA,montant_ht+timbre+TVA, marge, banq, ncheque, nbc, nom_preneur,'BL' from bl f, client c where f.nclient=c.nclient and date_fact = '"+date_jour+"'";
       
        
         String sql = "truncate table fact_tmp";
        try {
            St.execute(sql);
                sql="insert into fact_tmp " + query;
                St.execute(sql);
                
                sql="insert into fact_tmp " + query1;
                St.execute(sql);
                
       query="select nfact as Facture, nclient as Code_Client, raison_sociale, date_fact as Date ,montant_ht as HT, timbre, TVA,montant_ht+timbre+TVA, marge, banq, ncheque,  nom_preneur, type from fact_tmp";
       Rs = St.executeQuery(query);
        if (Rs.next()) { 
        Update_Table_Banq();
        //calcul_recette();
        } else {
        JOptionPane.showMessageDialog(null, "Pas de vente pour aujourd'hui le : "+date_jour);
        }
        } catch (SQLException ex) {
            Logger.getLogger(list_banq.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
                    
    }//GEN-LAST:event_btn_recette_jourActionPerformed

private void calcul_recette() {
    tot_banq=0.00;
    txt_tot_esp.setText("");
    txt_tot_term.setText("");
    txt_tot_banq.setText("");
    txt_tot_table.setText("");
    txt_tot_marge.setText("");
    
    try {
        String sql = "drop table tmp_banq";
        St.execute(sql);
        sql ="create table tmp_banq as SELECT banq, sum(montant_ht+tva+timbre) as ttc, sum(marge) as marge FROM fact_tmp group by banq";
        St.execute(sql);
        sql="select sum(ttc) as s_tot_esp, sum(marge) as marge from tmp_banq where banq =''";
        
                   Rs = St.executeQuery(sql);
                    if (Rs.next()) {
                        String add1 = Rs.getString("s_tot_esp");                        
                        String add2 = Rs.getString("marge");                        
                        if (add1 != null) {                           
                        Double som_tot_esp = Double.parseDouble(add1);
                        add1 = mntFmt.mntFmt(som_tot_esp);
                        txt_tot_esp.setText(add1);
                        Double marge = Double.parseDouble(add2);
                        add2 = mntFmt.mntFmt(marge);
                        txt_tot_marge.setText(add2);
                        tot_banq=tot_banq+som_tot_esp;
                        }
                    }
                    
                sql="select sum(ttc) as s_tot_term , sum(marge) as marge from tmp_banq where banq ='TERM'";
                  
                   Rs = St.executeQuery(sql);
                    if (Rs.next()) {                    
                        String add1 = Rs.getString("s_tot_term");
                        String add2 = Rs.getString("marge");                        
                        if (add1 != null) {                                                                            
                        Double som_tot_term = Double.parseDouble(add1);                          
                        add1 =mntFmt.mntFmt(som_tot_term);
                        txt_tot_term.setText(add1);
                        Double marge = Double.parseDouble(add2);
                        add2 = mntFmt.mntFmt(marge);
                        txt_tot_marge.setText(add2);
                        tot_banq=tot_banq+som_tot_term;
                        } 
                                              
    } 
                    
                    
        sql="select sum(ttc) as s_tot_table , sum(marge) as marge from tmp_banq ";
        
                    Rs = St.executeQuery(sql);
                    if (Rs.next()) {
                        String add1 = Rs.getString("s_tot_table");
                        String add2 = Rs.getString("marge");                        
                        if (add1 != null) {                            
                        Double som_tot_table = Double.parseDouble(add1);
                        add1 =mntFmt.mntFmt(som_tot_table);
                        txt_tot_table.setText(add1);
                        tot_banq=som_tot_table-tot_banq;
                        add1=mntFmt.mntFmt(tot_banq);
                        Double marge = Double.parseDouble(add2);
                        add2 = mntFmt.mntFmt(marge);
                        txt_tot_marge.setText(add2);
                        txt_tot_banq.setText(add1);
                    }
                    }
    }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur \n" + e.getMessage());
        }

}
        
    
    
private void selectionner () {
try
            {
            
          if ( txt_banque.getText().equals(""))   {
            String sql = "truncate table fact_tmp";
            St.execute(sql);
            sql="insert into fact_tmp " + query2;
            //JOptionPane.showMessageDialog(null, sql);
            St.execute(sql);
            query = "SELECT * from fact_tmp order by banq "; 
          }else {
              
           query = "DELETE from fact_tmp where banq <> '" + txt_banque.getText() + "'";
           //JOptionPane.showMessageDialog(null, query);
           St.execute(query);
           query = "SELECT * from fact_tmp "; 
           Rs = St.executeQuery(query);                        
           if (Rs.next()) {
            
           } else {
               
            JOptionPane.showMessageDialog(null, "Banque n'existe pas!" );
           }          
           }
           Update_Table_Banq();       
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la recherche\n" + e.getMessage());
        }  
}
    
  private void Update_Table_Banq() {
        try {   
            
            jPanel5.setVisible(true);
            calcul_recette();
            //query="select NFact, Nclient, date_fact,montant_ht, timbre, TVA, autre_taxe, banq, ncheque, nbc, nom_preneur from "+fichier_master+ condition;
            
            //JOptionPane.showMessageDialog(null, query);
            tm = new MyTableModel(query,base);
            Table_Banq.setModel(tm);
            Table_Banq.setDefaultRenderer(Double.class, new TKMntRenderer());
           
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table banque\n" + e.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */ 
  public static void list_banq(final String par, final String det, final String mas, final String bas) {
  //  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_banq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_banq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_banq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_banq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list_banq(par, det, mas, bas).setVisible(true);
              //  new list_banq().setVisible(true);
            }
        });
    }
    private Statement St;
    private ResultSet Rs;
    private Connection cnx;
    double tot_montant_ht,tot_timbre,tot_tva,tot_autre_taxe,tot_g,tot_banq, marge;
    public String fichier_master="fact",fichier_detail,parametre,query,query1,query2,sql,condition,list;
    public String cell_click,title,title1, base;
    public int nbre_enr, rang_champ_select=7, int_nfact;
    boolean sele_deselect = false;
    public JasperDesign jd;
   // MyTableModel tm;    public String fichier_master="fact",fichier_detail,parametre,query,sql,condition,list;
    //public String cell_click,title,title1;
    //public int nbre_enr, rang_champ_select=7, int_nfact;
    //boolean sele_deselect = false;
    //public JasperDesign jd;
    MyTableModel tm;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Banq;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_recette_jour;
    private javax.swing.JButton btn_selectioner;
    private javax.swing.JButton btn_valider;
    private com.toedter.calendar.JDateChooser date_debut;
    private com.toedter.calendar.JDateChooser date_fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_banque;
    private javax.swing.JTextField txt_bnq_dest;
    private javax.swing.JTextField txt_ncheque;
    private javax.swing.JTextField txt_nfact;
    private javax.swing.JTextField txt_raison_sociale;
    private javax.swing.JTextField txt_titre;
    private javax.swing.JTextField txt_tot_banq;
    private javax.swing.JTextField txt_tot_esp;
    private javax.swing.JTextField txt_tot_fact;
    private javax.swing.JTextField txt_tot_marge;
    private javax.swing.JTextField txt_tot_table;
    private javax.swing.JTextField txt_tot_term;
    // End of variables declaration//GEN-END:variables
}
