
package Stock;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.design.JasperDesign;

/**
 *
 * Habib Belkacemi  
 * le 18/10/2014
 * Liste des factures d'achats
 */
public class List_fachat extends javax.swing.JFrame {

    /**
     * Creates new form List_fachat
     */
    
    public List_fachat(String par, String det, String mas, String bas) {
        //JOptionPane.showMessageDialog(null, parametre);        
        parametre = par;        
        fichier_detail = det;
        fichier_master = mas;
        base=bas;
        if (mas.equals("bl")) {
         title="Bon de Livraison";
        } else if (mas.equals("fact")) {
         title="Facture";
        }
     
    //public List_fachat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_achat = new javax.swing.JTable();
        txt_titre = new javax.swing.JTextField();
        btn_quitter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_code_fourni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_selectionner_fourni = new javax.swing.JButton();
        txt_nom_fournisseur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_total_general = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des achats");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Table_achat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_achat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_achatMouseClicked(evt);
            }
        });
        Table_achat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_achatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_achat);

        txt_titre.setEditable(false);
        txt_titre.setBackground(new java.awt.Color(51, 51, 255));
        txt_titre.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txt_titre.setForeground(new java.awt.Color(255, 255, 255));
        txt_titre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_titre.setFocusable(false);
        txt_titre.setVerifyInputWhenFocusTarget(false);

        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        jLabel1.setText("Code Fournisseur  :");

        btn_selectionner_fourni.setText("Selectionner Fournisseur");
        btn_selectionner_fourni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectionner_fourniActionPerformed(evt);
            }
        });

        jLabel3.setText("Fournisseur           :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_nom_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btn_selectionner_fourni)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_code_fourni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_code_fourni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_selectionner_fourni, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nom_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())))
        );

        txt_total_general.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_generalActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Général :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(txt_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_total_general, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_quitter)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String pilote = "com.mysql.jdbc.Driver";
 
        String titre="";
            switch (parametre) {
                case "stock_f":
                    
                    titre = "Facturation";
                    
                    break;
                case "stock_bl" :   
                    titre = "Bon de livraison";
                    break;

            }
                            
            txt_titre.setText(titre);
            txt_titre.setBackground(Color.BLUE);
            txt_titre.setForeground(Color.WHITE);

        try {
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;             
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }        
        sql = "SELECT  `NFact`, f.`Nfournisseur`, c.`nom_fournisseur` as nom_fournisseur, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, `banque`, `ncheque` FROM "+fichier_master +" f, fournisseur c  where f.nfournisseur=c.nfournisseur order by f.nfact";        
        sql_sum="select sum(montant_ht)+sum(tva)+sum(timbre) as autre_taxe  from " +fichier_master;
        Update_Table_fachat();                          
    }//GEN-LAST:event_formWindowOpened

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void btn_selectionner_fourniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectionner_fourniActionPerformed
        if (txt_code_fourni.getText().equals("")) {
            txt_nom_fournisseur.setText("");
            JOptionPane.showMessageDialog(null, "Aucun code saisie! Réessayer SVP");
            sql_sum="select sum(montant_ht)+sum(tva)+sum(timbre) as autre_taxe  from " +fichier_master;

            sql = "SELECT  `NFact`, f.`Nfournisseur`, c.`nom_fournisseur` as nom_fournisseur, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, `banque`, `ncheque` FROM "+fichier_master +" f, fournisseur c  where f.nfournisseur=c.nfournisseur order by f.nfact";
            title1=" ";
        } else {            
            sql_sum="select sum(montant_ht)+sum(tva)+sum(timbre) as autre_taxe  from " +fichier_master +" where nfournisseur='"+txt_code_fourni.getText()+"'";
            sql = "SELECT  `NFact`, f.`Nfournisseur`, c.`nom_fournisseur` as nom_fournisseur, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, `banque`, `ncheque`  FROM "+fichier_master+" f, fournisseur c  where f.nfournisseur=c.nfournisseur and f.nfournisseur ='"+txt_code_fourni.getText()+"' order by date_fact" ;
            title1="Liste par Fournisseur :"+txt_code_fourni.getText();
        }

        Update_Table_fachat();
    }//GEN-LAST:event_btn_selectionner_fourniActionPerformed

    private void txt_total_generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_generalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_generalActionPerformed

    private void Table_achatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_achatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
        try {
            int row = Table_achat.getSelectedRow();                      
            String Table_click = (Table_achat.getModel().getValueAt(row, 1).toString());
            String sql_q = "SELECT  `NFact`, f.`Nfournisseur` as nfourni, c.`nom_fournisseur` as nom_fournisseur, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, `banque`, `ncheque`  FROM "+fichier_master+" f, fournisseur c  where f.nfournisseur=c.nfournisseur and f.nfournisseur ='"+Table_click+"' order by date_fact" ;

             Rs = St.executeQuery(sql_q);

            if (Rs.next()) {
                affiche_champs();                               
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
      }                // TODO add your handling code here:
    }//GEN-LAST:event_Table_achatKeyPressed

    private void Table_achatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_achatMouseClicked
        // TODO add your handling code here:
     {
        try {
            int row = Table_achat.getSelectedRow();
            int col = Table_achat.getSelectedColumn();
            String Table_click = (Table_achat.getModel().getValueAt(row, 1).toString());
            String sql_q = "SELECT  `NFact`, f.`Nfournisseur` as nfourni, c.`nom_fournisseur` as nom_fournisseur, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, `banque`, `ncheque`  FROM "+fichier_master+" f, fournisseur c  where f.nfournisseur=c.nfournisseur and f.nfournisseur ='"+Table_click+"' order by date_fact" ;
            
             //cell_click = Table_bl.getModel().getValueAt(row, col).toString();
             //JOptionPane.showMessageDialog(null, sql_q);
             Rs = St.executeQuery(sql_q);

            if (Rs.next()) {             
                affiche_champs();                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
      }            
    }//GEN-LAST:event_Table_achatMouseClicked

  private void affiche_champs() {
               try {
                    
                String add1 = Rs.getString("nfourni");
                txt_code_fourni.setText(add1);
               // String query="select raison_sociale from client where nclient ='"+add1+"'";              
                //Rs=St.executeQuery(query);
                //if (Rs.next()) {
                String add2=Rs.getString("nom_fournisseur");
                txt_nom_fournisseur.setText(add2);
               // }
               } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
}  
    
    
    private void Update_Table_fachat() {
        try {   
            
            Rs=St.executeQuery(sql);
            if (Rs.next()) {
            String add2 = Rs.getString("nom_fournisseur");
            txt_nom_fournisseur.setText(add2);
             
            Rs=St.executeQuery(sql_sum);
            if (Rs.next()) {
            String add1 = Rs.getString("autre_taxe");
             txt_total_general.setText(mntFmt.mntFmt(Double.parseDouble(add1)));
             tot_g= Double.parseDouble(add1);           
            }  
            if (txt_code_fourni.getText().equals("")) {
                txt_nom_fournisseur.setText("");
            }
            //query="select * from "+fichier_master;
            //JOptionPane.showMessageDialog(null, sql);
            tm = new MyTableModel(sql,base);
            Table_achat.setModel(tm);
            Table_achat.setDefaultRenderer(Double.class, new TKMntRenderer());
            //sql_sum="select sum(montant_ht)+sum(tva)+sum(timbre) as autre_taxe  from ventes";        
            //Rs=St.executeQuery(sql_sum);
           // if (Rs.next()) {
            //String add1 = Rs.getString("autre_taxe");
             //txt_total_general.setText(mntFmt.mntFmt(Double.parseDouble(add1)));
             //tot_g= Double.parseDouble(add1);
           // }
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table fachat\n" + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
public static void List_fachat(final String par, final String det, final String mas, final String bas) {    
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_fachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_fachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_fachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_fachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new List_fachat().setVisible(true);
                new List_fachat(par, det, mas, bas).setVisible(true);
            }
        });
    }
    private Statement St;
    private ResultSet Rs;
    private Connection cnx;
    double tot_montant_ht,tot_timbre,tot_tva,tot_autre_taxe,tot_g;
    public String fichier_master,fichier_detail,parametre,query,sql, base;
    public String cell_click,title,title1,sql_sum;
    public int nbre_enr, rang_champ_select=7, int_nfact;
    boolean sele_deselect = false;
    public JasperDesign jd;
    //public String parametre, fichier_detail, fichier_master;
  
    MyTableModel tm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_achat;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_selectionner_fourni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_code_fourni;
    private javax.swing.JTextField txt_nom_fournisseur;
    private javax.swing.JTextField txt_titre;
    private javax.swing.JTextField txt_total_general;
    // End of variables declaration//GEN-END:variables
}
