/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

/**
 *
 * @author IT
 */

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashMap;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


public class liste_bl extends javax.swing.JFrame {

    /**
     * Creates new form liste_bl
     */
    public liste_bl(String par, String det, String mas, String bas) {
        //JOptionPane.showMessageDialog(null, parametre);        
        parametre = par;        
        fichier_detail = det;
        fichier_master = mas;
        base = bas;
        if (mas.equals("bl")) {
         title="Bon de Livraison";
         sql ="SELECT  `NFact` as N°BL ";
        } else if (mas.equals("fact")) {
            sql ="SELECT  `NFact` ";
         title="Facture";
        } else {
         title="Facture Proformat";
        sql ="SELECT  `NFact` as Proformat N°";
        }
        sql_del="delete from ventes";    
        sql = "SELECT  `NFact` , f.`Nclient`, c.`raison_sociale` as raison_sociale, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, marge, `banq`, `ncheque`,   `nom_preneur` FROM "+fichier_master +" f, client c  where f.nclient=c.nclient  order by f.nfact";
        //JOptionPane.showMessageDialog(null, sql);
        title1=" ";
        /*
        query = "insert into ventes "+sql;
        St.execute(query);
        */
        sql_sum="select sum(autre_taxe) as autre_taxe  from " +fichier_master;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_bl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txt_code_cli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_tout_selectionner = new javax.swing.JButton();
        txt_raison_sociale = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_imprimer = new javax.swing.JButton();
        txt_titre = new javax.swing.JTextField();
        btn_quitter = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_tot_esp1 = new javax.swing.JTextField();
        txt_tot_banq1 = new javax.swing.JTextField();
        txt_tot_term1 = new javax.swing.JTextField();
        txt_tot_table1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tot_marge = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des Ventes");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Table_bl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_bl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_blMouseClicked(evt);
            }
        });
        Table_bl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_blKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_bl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
        );

        jLabel1.setText("Code Client  :");

        btn_tout_selectionner.setText("Selectionner Client");
        btn_tout_selectionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tout_selectionnerActionPerformed(evt);
            }
        });

        jLabel3.setText("Client          :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_raison_sociale, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btn_tout_selectionner)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_code_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_code_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tout_selectionner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_raison_sociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())))
        );

        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        txt_titre.setEditable(false);
        txt_titre.setBackground(new java.awt.Color(51, 51, 255));
        txt_titre.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txt_titre.setForeground(new java.awt.Color(255, 255, 255));
        txt_titre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_titre.setFocusable(false);
        txt_titre.setVerifyInputWhenFocusTarget(false);

        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        jLabel13.setText("Espèce :");

        jLabel14.setText("Banque :");

        jLabel15.setText("Term     :");

        jLabel16.setText("Total     :");

        txt_tot_esp1.setEditable(false);
        txt_tot_esp1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_esp1.setEnabled(false);

        txt_tot_banq1.setEditable(false);
        txt_tot_banq1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_banq1.setEnabled(false);

        txt_tot_term1.setEditable(false);
        txt_tot_term1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_term1.setEnabled(false);

        txt_tot_table1.setEditable(false);
        txt_tot_table1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_table1.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tot_table1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tot_term1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tot_esp1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tot_banq1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_tot_esp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_tot_banq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_tot_term1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_tot_table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setText("Marge :");

        txt_tot_marge.setEditable(false);
        txt_tot_marge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_marge.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(txt_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(196, 196, 196)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tot_marge, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txt_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tot_marge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(btn_quitter)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(77, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String pilote = "com.mysql.jdbc.Driver";
        String titre="";
            switch (parametre) {
                case "stock_f":
                    
                    titre = "Facturation";
                    
                    break;
                case "stock_bl" :   
                    titre = "Bon de livraison";
                    break;
                case "" :   
                    titre = "Proformat";
                    break;
            }
                            
            txt_titre.setText(titre);
            txt_titre.setBackground(Color.BLUE);
            txt_titre.setForeground(Color.WHITE);

        try {
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        Update_Table_bl();        
    }//GEN-LAST:event_formWindowOpened

    private void Table_blMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_blMouseClicked
       try {
            int row = Table_bl.getSelectedRow();
            int col = Table_bl.getSelectedColumn();
            String Table_click = (Table_bl.getModel().getValueAt(row, 0).toString());
           // String sql = "select * from "+fichier_master+" where nfact = '" + Table_click + "'";
// 
             String sql_q = "SELECT  `NFact`,f.`nclient` as nclient, c.`raison_sociale` as raison_sociale, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, marge, `banq`, `ncheque`,    `nom_preneur` FROM "+fichier_master +" f, client c where f.nclient= c.nclient  and f.nfact = '" + Table_click + "' order by f.nclient";
             //cell_click = Table_bl.getModel().getValueAt(row, col).toString();
              //JOptionPane.showMessageDialog(null, sql_q);
             Rs = St.executeQuery(sql_q);

            if (Rs.next()) {
                affiche_champs();                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }        
    }//GEN-LAST:event_Table_blMouseClicked

    private void calcul_nfact(){
    try {
            fichier_master ="fact";
            fichier_detail ="detail_fact";
            String query="select count(*) as nbre_enr FROM "+fichier_master+";";
            St.execute(query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add1 = Rs.getString("nbre_enr");
            if (Integer.parseInt(add1) > 0) {
            query="select max(nfact) as nfact_max FROM "+fichier_master+";";
            JOptionPane.showMessageDialog(null, query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add2 = Rs.getString("nfact_max");
            JOptionPane.showMessageDialog(null, add1);
            int_nfact= Integer.parseInt(add2)+1;
            } 
            }else {
            int_nfact=1;
             }            
            txt_code_cli.setText(Integer.toString(int_nfact));
            }
    } catch (Exception e) {
    
    JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
    }
    }
    
    
    private void btn_tout_selectionnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tout_selectionnerActionPerformed
       if (txt_code_cli.getText().equals("")) {
        txt_raison_sociale.setText("");
        JOptionPane.showMessageDialog(null, "Aucun code saisie! Réessayer SVP");
        sql_sum="select sum(autre_taxe) as autre_taxe, sum(marge) as marge  from " +fichier_master;
         
        sql = "SELECT  `NFact`, f.`Nclient`, c.`raison_sociale` as raison_sociale, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, marge, `banq`, `ncheque`,   `nom_preneur` FROM "+fichier_master +" f, client c  where f.nclient=c.nclient order by f.nfact";  
       title1=" ";    
       } else {
          sql_sum="select sum(autre_taxe) as autre_taxe, sum(marge) as marge from " +fichier_master +" where nclient='"+txt_code_cli.getText()+"'";
        sql = "SELECT  `NFact`, f.`Nclient`, c.`raison_sociale` as raison_sociale, `date_fact`, `montant_ht`, `timbre`, `TVA`, `montant_ht`+`timbre`+`TVA` as TTC, marge, `banq`, `ncheque`,   `nom_preneur` FROM "+fichier_master+" f, client c  where f.nclient=c.nclient and f.nclient ='"+txt_code_cli.getText()+"' order by date_fact" ;                  
       title1="Liste par Client :"+txt_code_cli.getText();
       }
       Update_Table_bl(); 
    }//GEN-LAST:event_btn_tout_selectionnerActionPerformed

    private void Table_blKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_blKeyReleased
       if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
        try {
            int row = Table_bl.getSelectedRow();
            int col = Table_bl.getSelectedColumn();
            String Table_click = (Table_bl.getModel().getValueAt(row, 0).toString());
             String sql_q = "SELECT  `NFact`,f.`nclient` as nclient, c.`raison_sociale` as raison_sociale, `date_fact`, `montant_ht`, `timbre`, `TVA`,  marge, `banq`, `ncheque`,    `nom_preneur`FROM "+fichier_master +" f, client c where f.nclient= c.nclient  and f.nfact = '" + Table_click + "' order by f.nclient";
            //String sql_q = "select * from bl where nfact = '" + Table_click + "'";
             //cell_click = Table_bl.getModel().getValueAt(row, col).toString();
             //JOptionPane.showMessageDialog(null, sql_q);
             Rs = St.executeQuery(sql_q);

            if (Rs.next()) {
                affiche_champs();                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
      }        
    }//GEN-LAST:event_Table_blKeyReleased

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
    
        try {
        jd = JRXmlLoader.load("C:\\outil_dev\\report_ventes.jrxml");
        JRDesignQuery newquery = new JRDesignQuery();
        query="select 1";
        // query="SELECT  `NFact`, `Nclient`, `raison_sociale` , `date_fact`, `montant_ht`, `timbre`, `TVA`, `autre_taxe`, `banq`, `ncheque`,    `nom_preneur` FROM  ventes";
        newquery.setText(query);
        jd.setQuery(newquery);
        HashMap hm = new HashMap();
        hm.put("title_p", title);
        hm.put("title_p1", title1);
        hm.put("som_sum_p",tot_g);        
        hm.put("sous_titre_p", "");
        hm.put("sql_p_req","");
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, hm, cnx);            
        JasperViewer.viewReport(jp, false);          
       }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans l'insertion table\n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed
         
    
       private void affiche_champs() {
               try {
                    
                String add1 = Rs.getString("nclient");
                txt_code_cli.setText(add1);
               // String query="select raison_sociale from client where nclient ='"+add1+"'";
                //JOptionPane.showMessageDialog(null, query);
                //Rs=St.executeQuery(query);
                //if (Rs.next()) {
                String add2=Rs.getString("raison_sociale");
                txt_raison_sociale.setText(add2);
               // }
               } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }
}
    /**
     * @param args the command line arguments
*/

     
private void calcul_recette() {
    tot_banq=0.00;
    txt_tot_esp1.setText("");
    txt_tot_term1.setText("");
    txt_tot_banq1.setText("");
    txt_tot_table1.setText("");
    txt_tot_marge.setText("");
    //JOptionPane.showMessageDialog(null, "passer la ligne 528");
    try {
        String sql = "drop table tmp_banq";
        St.execute(sql);
        sql ="create table tmp_banq as SELECT banq, sum(montant_ht+tva+timbre) as ttc, sum(marge) as marge FROM ventes group by banq";
        St.execute(sql);
        sql="select sum(ttc) as s_tot_esp, sum(marge) as marge from tmp_banq where banq =''";
        
                   Rs = St.executeQuery(sql);
                    if (Rs.next()) {
                        String add1 = Rs.getString("s_tot_esp");
                        String add2 = Rs.getString("marge");
                        if (add1 != null) {                           
                        Double som_tot_esp = Double.parseDouble(add1);                        
                        Double marge = Double.parseDouble(add2);
                        add1 = mntFmt.mntFmt(som_tot_esp);
                        add2 = mntFmt.mntFmt(marge);
                        txt_tot_esp1.setText(add1);
                        txt_tot_marge.setText(add2);
                        tot_banq=tot_banq+som_tot_esp;
                        }
                    }
                    
                sql="select sum(ttc) as s_tot_term, sum(marge) as marge from tmp_banq where banq ='TERM'";
                  
                   Rs = St.executeQuery(sql);
                    if (Rs.next()) {                    
                        String add1 = Rs.getString("s_tot_term");
                        String add2 = Rs.getString("marge");
                        if (add1 != null) {                                                                            
                        Double som_tot_term = Double.parseDouble(add1);                          
                        add1 =mntFmt.mntFmt(som_tot_term);
                        Double marge = Double.parseDouble(add2);
                        add2 = mntFmt.mntFmt(marge);
                        txt_tot_marge.setText(add2);
                        txt_tot_term1.setText(add1);
                        tot_banq=tot_banq+som_tot_term;
                        } 
                                              
    } 
                    
                    
        sql="select sum(ttc) as s_tot_table, sum(marge) as marge from tmp_banq ";
        
                    Rs = St.executeQuery(sql);
                    if (Rs.next()) {
                        String add1 = Rs.getString("s_tot_table");
                        String add2 = Rs.getString("marge");
                        if (add1 != null) {                            
                        Double som_tot_table = Double.parseDouble(add1);
                        add1 =mntFmt.mntFmt(som_tot_table);                        
                        txt_tot_table1.setText(add1);                       
                        Double marge = Double.parseDouble(add2);
                        add2 = mntFmt.mntFmt(marge);
                        txt_tot_marge.setText(add2);
                        tot_banq=som_tot_table-tot_banq;
                        add1=mntFmt.mntFmt(tot_banq);
                        txt_tot_banq1.setText(add1);
                    }
                    }
    }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur \n" + e.getMessage());
        }

}       
       
private void Update_Table_bl() {
        try { 
            //JOptionPane.showMessageDialog(null, sql);
           Rs=St.executeQuery(sql);
           if (Rs.next()) { 
            query ="delete from ventes";
            St.executeUpdate(query);
            query = "insert into ventes "+sql;
            St.executeUpdate(query);
           // JOptionPane.showMessageDialog(null, query);
            calcul_recette();
           // JOptionPane.showMessageDialog(null, "passer calcul recette");
            query="select * from ventes";
            tm = new MyTableModel(query,base);
            Table_bl.setModel(tm);
            Table_bl.setDefaultRenderer(Double.class, new TKMntRenderer());
            sql_sum="select sum(montant_ht)+sum(tva)+sum(timbre) as autre_taxe, sum(marge) as marge  from ventes";        
            Rs=St.executeQuery(sql_sum);
            if (Rs.next()) {
                 String add1 = Rs.getString("autre_taxe");
                 String add2 = Rs.getString("marge");
             //txt_total_general.setText(mntFmt.mntFmt(Double.parseDouble(add1)));
                 
             tot_g= Double.parseDouble(add1);
             marge = Double.parseDouble(add2);
            }
           }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec \n" + e.getMessage());
        }
    }    
    
 public static void list_bl(final String par, final String det, final String mas, final String bas) {
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(liste_bl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(liste_bl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(liste_bl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(liste_bl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new liste_bl(par, det, mas, bas).setVisible(true);
            }
        });
    }
    
    private Statement St;
    private ResultSet Rs;
    private Connection cnx;
    double tot_montant_ht,tot_timbre,tot_tva,tot_autre_taxe,tot_g,tot_banq, marge;
    public String cell_click,title,title1;
    public int nbre_enr, rang_champ_select=7, int_nfact;
    boolean sele_deselect = false;
    public JasperDesign jd;
    //public String parametre, fichier_detail, fichier_master;
    public String fichier_master,code_cli,xdate_fact,fichier_detail,parametre,query,sql,sql_sum,sql_del, base;
    MyTableModel tm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_bl;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_tout_selectionner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_code_cli;
    private javax.swing.JTextField txt_raison_sociale;
    private javax.swing.JTextField txt_titre;
    private javax.swing.JTextField txt_tot_banq1;
    private javax.swing.JTextField txt_tot_esp1;
    private javax.swing.JTextField txt_tot_marge;
    private javax.swing.JTextField txt_tot_table1;
    private javax.swing.JTextField txt_tot_term1;
    // End of variables declaration//GEN-END:variables
}

