/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

/**
 *
 * @author IT
 */

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
 


public class Login_St_stock extends javax.swing.JFrame {
        
    /**
     * Creates new form Login_St_stock
     */
    public Login_St_stock() {
        initComponents();
       // fillCombo1_activite();
        //cnx = javaconnect.ConnecrDb();
// 1. Get default keys
      Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
       ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1_activite = new javax.swing.JComboBox();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identification", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 51, 153))); // NOI18N

        jLabel1.setText("Nom :");

        jLabel2.setText("Mot de passe :");

        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });

        jButton1.setText("Valider");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Activite :");

        jComboBox1_activite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1_activiteFocusLost(evt);
            }
        });
        jComboBox1_activite.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1_activitePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txt_username))
                            .addComponent(jComboBox1_activite, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1_activite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {        
       if (ouvert) {
        passage();
       }
       ouvert=false;
      } catch (Exception e) { JOptionPane.showMessageDialog(null, "Erreur dans l'ouverture de la fenêtre" + e.getMessage());
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        try {        
       if (ouvert) {
        passage();
       }
       ouvert=false;
      } catch (Exception e) { JOptionPane.showMessageDialog(null, "Erreur dans l'ouverture de la fenêtre" + e.getMessage());
        
    }
    }//GEN-LAST:event_jButton1FocusLost

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
       fillCombo1_activite();
    }//GEN-LAST:event_txt_passwordFocusLost

    private void jComboBox1_activitePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1_activitePopupMenuWillBecomeInvisible
     var_connection = (String) jComboBox1_activite.getSelectedItem();         
    }//GEN-LAST:event_jComboBox1_activitePopupMenuWillBecomeInvisible

    private void jComboBox1_activiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1_activiteFocusLost
        var_connection = (String) jComboBox1_activite.getSelectedItem();
    }//GEN-LAST:event_jComboBox1_activiteFocusLost

    
    private void passage(){
      String sql ="select * from user_info where username=? and pass_word= ? and activite = ?";
      String pilote = "com.mysql.jdbc.Driver";       
       
        try {
            // connexion avec la base de donnée 
         Class.forName(pilote);
          
         //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
         Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
          // St = cnx.createStatement();
          St = cnx.prepareStatement(sql);
          St.setString(1,txt_username.getText());
          St.setString(2, txt_password.getText());
          St.setString(3, var_connection);
          //JOptionPane.showMessageDialog(null, var_connection);
          //JOptionPane.showMessageDialog(null, sql);
          Rs = St.executeQuery();
          if ( Rs.next()) {
          //JOptionPane.showMessageDialog(null, "Nom et mot de passe correct !");
              String bl="";
              sql="update user_info set has_login='"+bl +"'";
             //JOptionPane.showMessageDialog(null, sql);
              St.executeUpdate(sql);
              bl="Yes";
              sql="update user_info set has_login= '"+bl+"'" + " where username = '" +txt_username.getText() + "' and activite ='"+var_connection +"'";
              //JOptionPane.showMessageDialog(null, sql);
              St.executeUpdate(sql);
          
          sql=" select code_activite from stock_table_activite where activite = '"+var_connection +"'";
          Rs = St.executeQuery(sql);
          while (Rs.next()) {
                base = Rs.getString("code_activite");
            }  
           sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            year= Rs.getString("db_name");
            }
          //JOptionPane.showMessageDialog(null, base);
          close();
          Gestion_Stock gest = new Gestion_Stock(base, var_connection,year);
          gest.setVisible(true);
          
          } else {
             // JOptionPane.showMessageDialog(null, var_connection);
             JOptionPane.showMessageDialog(null, "Nom et mot de passe incorrect !");
             txt_username.setText("");
             txt_password.setText("");
             txt_username.requestFocus();
          }
          
          
    } catch (Exception e) { JOptionPane.showMessageDialog(null, "Erreur dans la connexion" + e.getMessage());
    
    
    }
    
    }
private void fillCombo1_activite() {
        //JOptionPane.showMessageDialog(null, "Je rempli le Combox");
       jComboBox1_activite.removeAllItems();
        String sql = "SELECT distinct activite FROM user_info where username = '" +txt_username.getText() +"'";
        String nme="";
        try {
            Connection var_cnx1= DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            //String user_bd1="root";
            //String passwd_bd1="";
            St1 = var_cnx1.createStatement();  
            //cnx1 = DriverManager.getConnection(var_cnx1, user_bd1, passwd_bd1);
            //Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St1 = cnx1.createStatement();           
            Rs1 = St1.executeQuery(sql);
            while (Rs1.next()) {
                nme = Rs1.getString("activite");
                jComboBox1_activite.addItem(nme);
            }            
            var_connection=nme;
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la liste jComboBox1\n" + e.getMessage());
        }
    }    
    
     public void close() {
                   
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_St_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_St_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_St_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_St_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_St_stock().setVisible(true);
            }
        });
    }
    
    public PreparedStatement St = null;
    private Statement St1;
    private ResultSet Rs,Rs1;
    public Connection cnx = null;
    public boolean ouvert=true;
    public String query,var_connection,base,year;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1_activite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
