/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author IT
 */
public class rappel_facture extends javax.swing.JFrame {

    /**
     * Creates new form rappel_facture
     */
    public rappel_facture(String par,String det, String mas, String bas) {
        parametre =par; 
        fichier_detail= det;
        fichier_master=mas;
        base=bas;
        
        
        
        initComponents();
        switch (parametre) {
                case "stock_f":                                        
                    txt_numero_fact.setText("Facture N°:");
                    titre = "n_fact";
                    break;
                case "stock_bl" :   
                    txt_numero_fact.setText("BL N°:");
                    titre = "n_bl";
                    break;
                case "" :                       
                    txt_numero_fact.setText("Proformat N°:");
                    titre = "n_prof";
                    break;
            }
        jPanel3.setVisible(false);
        if (fichier_master.equals("bl")) {
          jPanel3.setVisible(true);
        }
 // 1. Get default keys
      Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
       ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        date_fact = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_code_cli = new javax.swing.JTextField();
        txt_nfact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_chercher = new javax.swing.JButton();
        txt_raison_sociale = new javax.swing.JTextField();
        txt_numero_fact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Factures = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_total_tva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_timbre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_prix_tot = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_s_total = new javax.swing.JTextField();
        btn_supprimer = new javax.swing.JButton();
        btn_imprimer = new javax.swing.JButton();
        btn_quitter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_impression_ptit_format = new javax.swing.JButton();
        btn_impression_de_bon = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rappel des Ventes");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        date_fact.setEnabled(false);

        jLabel1.setText("Date :");

        jLabel2.setText("Code client :");

        txt_code_cli.setEditable(false);
        txt_code_cli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_code_cli.setEnabled(false);
        txt_code_cli.setVerifyInputWhenFocusTarget(false);
        txt_code_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_code_cliActionPerformed(evt);
            }
        });
        txt_code_cli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_code_cliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_code_cliFocusLost(evt);
            }
        });
        txt_code_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_code_cliKeyReleased(evt);
            }
        });

        txt_nfact.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Nom :");

        btn_chercher.setText("Chercher");
        btn_chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chercherActionPerformed(evt);
            }
        });
        btn_chercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_chercherFocusLost(evt);
            }
        });

        txt_raison_sociale.setEditable(false);
        txt_raison_sociale.setEnabled(false);

        txt_numero_fact.setEditable(false);
        txt_numero_fact.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_numero_fact.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_numero_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_nfact, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(btn_chercher)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(txt_code_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_raison_sociale, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numero_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_chercher)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt_code_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txt_raison_sociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Table_Factures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Seq.", "Code Article", "Description", "Prix Unitaire", "TVA", "Quantité", "Prix Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_Factures.setToolTipText("");
        Table_Factures.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table_Factures.setName(""); // NOI18N
        Table_Factures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_FacturesMouseClicked(evt);
            }
        });
        Table_Factures.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_FacturesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Factures);

        jLabel15.setText("T.V.A");

        txt_total_tva.setEditable(false);
        txt_total_tva.setBackground(new java.awt.Color(255, 255, 255));
        txt_total_tva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_tva.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_total_tva.setEnabled(false);

        jLabel12.setText("Prix Total ");

        txt_timbre.setEditable(false);
        txt_timbre.setBackground(new java.awt.Color(255, 255, 255));
        txt_timbre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_timbre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_timbre.setEnabled(false);

        jLabel14.setText("Timbre ");

        txt_prix_tot.setEditable(false);
        txt_prix_tot.setBackground(new java.awt.Color(255, 255, 255));
        txt_prix_tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_prix_tot.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_prix_tot.setEnabled(false);

        jLabel13.setText("S / Total");

        txt_s_total.setEditable(false);
        txt_s_total.setBackground(new java.awt.Color(255, 255, 255));
        txt_s_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_s_total.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_s_total.setEnabled(false);

        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_imprimer.setText("Imprimer");
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });

        btn_quitter.setText("Quitter");
        btn_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_prix_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn_supprimer)
                        .addGap(71, 71, 71)
                        .addComponent(btn_imprimer)
                        .addGap(129, 129, 129)
                        .addComponent(btn_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_s_total, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(825, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14))
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_total_tva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addComponent(txt_timbre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_s_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btn_supprimer)
                    .addComponent(btn_imprimer)
                    .addComponent(btn_quitter))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_prix_tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_timbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total_tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        btn_impression_ptit_format.setText("Impression en Petit  Format");
        btn_impression_ptit_format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_impression_ptit_formatActionPerformed(evt);
            }
        });

        btn_impression_de_bon.setText("Impression de Bon");
        btn_impression_de_bon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_impression_de_bonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_impression_de_bon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btn_impression_ptit_format, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_impression_ptit_format)
                    .addComponent(btn_impression_de_bon)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_code_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_code_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_code_cliActionPerformed

    private void txt_code_cliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_code_cliFocusGained
        txt_code_cli.setText("");
    }//GEN-LAST:event_txt_code_cliFocusGained

    
    

    
    private void txt_code_cliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_code_cliFocusLost

    }//GEN-LAST:event_txt_code_cliFocusLost

    private void txt_code_cliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_cliKeyReleased
                 
    }//GEN-LAST:event_txt_code_cliKeyReleased

    
    private void Table_FacturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_FacturesMouseClicked
        try {
            int row = Table_Factures.getSelectedRow();
            String Table_click = (Table_Factures.getModel().getValueAt(row, 0).toString());
            String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_temp AS F, article AS A where F.narticle=A.narticle and F.id ='"+ Table_click + "'";            
            //cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
                //affiche_champs();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
        }

    }//GEN-LAST:event_Table_FacturesMouseClicked

        
    private void Table_FacturesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_FacturesKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_UP || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN || evt.getKeyCode() == KeyEvent.VK_HOME || evt.getKeyCode() == KeyEvent.VK_END) {
            try {
                int row = Table_Factures.getSelectedRow();
                String Table_click = (Table_Factures.getModel().getValueAt(row, 0).toString());
                String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_temp AS F, article AS A where F.narticle=A.narticle and F.id ='"+ Table_click + "'";

                //cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
                //St = cnx.createStatement();
                Rs = St.executeQuery(sql);
                if (Rs.next()) {
                  //  affiche_champs();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_Table_FacturesKeyReleased

   

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
        String pilote = "com.mysql.jdbc.Driver";
        
        try {
            //JOptionPane.showMessageDialog(null, "Salam ");
            // connexion avec la base de donnée 
            Class.forName(pilote);
            cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            St = cnx.createStatement();  
            
            String sql = "select db_name from stock_table_parameter where code_activite='"+base+"'";
            Rs = St.executeQuery(sql);
            if (Rs.next()) {
            String var_cnx= "jdbc:mysql://localhost:3306/"+Rs.getString("db_name");
            var_cnx=var_cnx+"_"+base;    
            String user_bd="root";
            String passwd_bd="";
            cnx = DriverManager.getConnection(var_cnx, user_bd, passwd_bd);
            St = cnx.createStatement();
            }
            //cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=yes&amp;characterEncoding=UTF-8", "root", "");
            //St = cnx.createStatement();
            query ="truncate table facture_temp";
           
            St.execute(query);
            query="select count(*) as nbre_enr FROM "+fichier_master+";";
            // JOptionPane.showMessageDialog(null, query);
            St.execute(query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add1 = Rs.getString("nbre_enr");
            if (Integer.parseInt(add1) > 0) {
            query="select max(nfact) as nfact_max FROM "+fichier_master+";";
            // JOptionPane.showMessageDialog(null, query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add2 = Rs.getString("nfact_max");
           // JOptionPane.showMessageDialog(null, add1);
            int_nfact= Integer.parseInt(add2)+1;
            } 
            }else {
            int_nfact=1;
             }            
            txt_nfact.setText(Integer.toString(int_nfact));            
            }
            txt_nfact.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de connexcion\n" + e.getMessage());
        }
        Update_Table_Factures();  
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chercherActionPerformed
 // rappeler une facture si la table facture est vide.
       chercher();        
    }//GEN-LAST:event_btn_chercherActionPerformed

    
    
    
    private void chercher() {
         try {
           // JOptionPane.showMessageDialog(null,"Salam");
            query ="truncate table facture_temp";
            St.executeUpdate(query);
            query="select count(*) as nbre_enr FROM facture_temp";
           // JOptionPane.showMessageDialog(null,query);
            Rs=St.executeQuery(query);
            if (Rs.next()) {
            String add1 = Rs.getString("nbre_enr");
            // JOptionPane.showMessageDialog(null,add1);
             if (Integer.parseInt(add1) > 0) {  JOptionPane.showMessageDialog(null, " Cette opération n'est pas autorisée à ce stade !" );
            }
             else {
            query = "select fm.nfact as \"nfact\", fm.nclient as \"nclient\", cl.raison_sociale as \"raison_sociale\", fm.date_fact as \"date_fact\" ,fm.montant_ht as \"montant_ht\",fm.timbre as \"timbre\",fm.tva as \"tva\", fm.autre_taxe as \"autre_taxe\" from client cl,"+fichier_master+" fm where fm.nclient = cl.nclient and fm.nfact ='"+txt_nfact.getText()+"'" ;    
            Rs=St.executeQuery(query);
            if (Rs.next()) { 
                String add2 = Rs.getString("nclient");
                txt_code_cli.setText(add2);
                String add7= Rs.getString("raison_sociale");
                txt_raison_sociale.setText(add7);
                Date add3 = Rs.getDate("date_fact");
                date_fact.setDate(add3);
                String add4 = Rs.getString("montant_ht");
                txt_s_total.setText(mntFmt.mntFmt(Double.parseDouble(add4)));
                String add5 = Rs.getString("timbre");
                txt_timbre.setText(mntFmt.mntFmt(Double.parseDouble(add5)));
                String add6 = Rs.getString("tva");
                txt_total_tva.setText(mntFmt.mntFmt(Double.parseDouble(add6)));
                mnt = Double.parseDouble(add6)+Double.parseDouble(add5)+Double.parseDouble(add4);
                txt_prix_tot.setText(mntFmt.mntFmt(Double.parseDouble(add6)+Double.parseDouble(add5)+Double.parseDouble(add4)));
                
               // JOptionPane.showMessageDialog(null,mnt);
                exp_spell = Numb_to_Spell.spell(mnt, "");
                
               // JOptionPane.showMessageDialog(null,exp_spell);
            query = "insert into facture_temp (nfact, narticle, qte,tva,prix,total_ligne)  select nfact, narticle, qte,tva,prix,total_ligne from "+fichier_detail+" where nfact ='"+txt_nfact.getText()+"'" ;
            //query ="insert into "+ fichier_detail+" (nfact, narticle, qte,tva,prix,total_ligne) select nfact, narticle, qte,tva,prix,total_ligne from facture";
            //JOptionPane.showMessageDialog(null,query);
            St.executeUpdate(query);
            query ="update facture_temp set type_fact ='"+parametre+"'";
            St.executeUpdate(query);
            String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_temp AS F, article AS A where F.narticle=A.narticle order by F.id" ;                      
            // JOptionPane.showMessageDialog(null,txt_nfact.getText());
            tm = new MyTableModel(sql, base);
            Table_Factures.setModel(tm);
            Table_Factures.setDefaultRenderer(Double.class, new TKMntRenderer());
            } else {
                   //JOptionPane.showMessageDialog(null,"Le numéro que vous avez introduit n'existe pas !");
                vider_champs();
            
            
            JOptionPane.showMessageDialog(null,"Le numéro que vous avez introduit n'existe pas !");
            txt_nfact.setText("");
                 }
            }
            
            }
        } catch(Exception e) {  JOptionPane.showMessageDialog(null, "Erreur  \n" + e.getMessage()); 
        }
    }
    
            
    
    private void vider_champs() {
                   txt_code_cli.setText("");
                   txt_raison_sociale.setText("");
                   date_fact.setDate(null);
                   txt_s_total.setText("");
                   txt_timbre.setText("");
                   txt_total_tva.setText("");
                   txt_prix_tot.setText("");
                   String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_temp AS F, article AS A where F.narticle=A.narticle order by F.id" ;             
                   tm = new MyTableModel(sql, base);
                   Table_Factures.setModel(tm);
                   Table_Factures.setDefaultRenderer(Double.class, new TKMntRenderer());
    }
    
    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
           try {      
               
 Object[] options = {"Oui, je confirme!","Ooups, Non, Merci"};                 
   int r = JOptionPane.showOptionDialog(null, " Etes vous sur de vouloir Supprimer ?", "Confirmation",  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null, options,options[1]);           
           
            if (r == 0) {    
                sql = "truncate table facture";
                  St.executeUpdate(sql);
                sql = "insert into facture  select *  from facture_temp ";
                  St.executeUpdate(sql);
               String tab="facture";      
               nettoyer_facture.nettoyer_facture(base, tab);
                      sql = " delete from "+fichier_detail+" where nfact ='"+txt_nfact.getText()+"'" ;
                     St.executeUpdate(sql);  
                      sql = " delete from "+fichier_master+" where nfact ='"+txt_nfact.getText()+"'" ;
                     St.executeUpdate(sql);
                     
                     if (! parametre.equals("")) {
                        query = "select c_affaire_"+fichier_master+" as ca from client where nclient= '"+txt_code_cli.getText()+"'";
                        St.execute(query);
                        Rs=St.executeQuery(query);
                        if (Rs.next()) {
                            String add1 = Rs.getString("ca");            
                            double xtot_ttc = Double.parseDouble(add1)-mnt;            
                            query = "update client set c_affaire_"+fichier_master+"="+xtot_ttc+" where nclient= '"+txt_code_cli.getText()+"'";
                            //JOptionPane.showMessageDialog(null,query);
                            //JOptionPane.showMessageDialog(null,mnt);
                            //JOptionPane.showMessageDialog(null,add1);
                            St.executeUpdate(query);
                        }
                    }

            sql ="truncate table facture_temp";
            St.executeUpdate(sql);
            query = "select "+titre+"  as nbre_enr FROM mysql.stock_table_parameter  where code_activite='"+base+"'";;
            St.execute(query);
            Rs = St.executeQuery(query);
            if (Rs.next()) {
               String add1 = Rs.getString("nbre_enr");
               // JOptionPane.showMessageDialog(null,Integer.parseInt(add1));
                //JOptionPane.showMessageDialog(null,Integer.parseInt(txt_nfact.getText()));
                if (Integer.parseInt(add1)-1 == Integer.parseInt(txt_nfact.getText())) {
                    
                        int_nfact = Integer.parseInt(add1);                                                        
                        txt_nfact.setText(Integer.toString(int_nfact));
                        int_nfact = Integer.parseInt(add1) - 1;
                        sql = "update mysql.stock_table_parameter set "+titre+ "="+int_nfact+ "  where code_activite='"+base+"'";
                  //      JOptionPane.showMessageDialog(null,sql);
                        St.executeUpdate(sql);
                } 
            
                
            }
            
            
            
            
            vider_champs();
            txt_nfact.setText("");
           
            
            
            
           } 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }  
     
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
    
    
             
            try {
                        
                         
               // JOptionPane.showMessageDialog(null, txt_domaine_actvite);
                switch (parametre)
        {  
            case "stock_f":
                 jd = JRXmlLoader.load("C:\\outil_dev\\report_fact.jrxml");
                //jd = JRXmlLoader.load("report_fact.jrxml");
             sql = "SELECT fact.`NFact` AS fact_NFact,      fact.`Nclient` AS fact_Nclient,      fact.`date_fact` AS fact_date_fact,      fact.`montant_ht` AS fact_montant_ht,      fact.`timbre` AS fact_timbre,      fact.`TVA` AS fact_TVA,      fact.`autre_taxe` AS fact_autre_taxe,      client.`Nclient` AS client_Nclient,      client.`Raison_sociale` AS client_Raison_sociale,      client.`adresse` AS client_adresse,      client.`NRC` AS client_NRC,      client.`Date_RC` AS client_Date_RC,      client.`Lieu_RC` AS client_Lieu_RC,      client.`I_Fiscal` AS client_I_Fiscal,      client.`N_article` AS client_N_article       FROM      `client` client INNER JOIN `fact` fact ON client.`Nclient` = fact.`Nclient` WHERE fact.nfact ='"+txt_nfact.getText()+"'";
             //JOptionPane.showMessageDialog(null, "facture");
                break;

            case "stock_bl":
               // JOptionPane.showMessageDialog(null, "bl");
                 jd = JRXmlLoader.load("C:\\outil_dev\\report_bl.jrxml");
                //jd = JRXmlLoader.load("report_bl.jrxml");
                //jd = JRXmlLoader.load("E:\\Dev\\St_Article\\src\\Stock\\Report_annexe01.jrxml");
                 sql = "SELECT bl.`NFact` AS fact_NFact,      bl.`Nclient` AS fact_Nclient,      bl.`date_fact` AS fact_date_fact,      bl.`montant_ht` AS fact_montant_ht,      bl.`timbre` AS fact_timbre,      bl.`TVA` AS fact_TVA,      bl.`autre_taxe` AS fact_autre_taxe,      client.`Nclient` AS client_Nclient,      client.`Raison_sociale` AS client_Raison_sociale,      client.`adresse` AS client_adresse,      client.`NRC` AS client_NRC,      client.`Date_RC` AS client_Date_RC,      client.`Lieu_RC` AS client_Lieu_RC,      client.`I_Fiscal` AS client_I_Fiscal,      client.`N_article` AS client_N_article,  bl.`nbc` AS fact_nbc, bl.`date_bc` AS fact_date_bc, bl.`nom_preneur` AS fact_nom_preneur       FROM      `client` client INNER JOIN `bl` bl ON client.`Nclient` = bl.`Nclient` WHERE bl.nfact ='"+txt_nfact.getText()+"'";
                 
                break;

            case "":
                 jd = JRXmlLoader.load("C:\\outil_dev\\report_prof.jrxml");
                // jd = JRXmlLoader.load("report_prof.jrxml");
                 sql = "SELECT fprof.`NFact` AS fact_NFact,      fprof.`Nclient` AS fact_Nclient,      fprof.`date_fact` AS fact_date_fact,      fprof.`montant_ht` AS fact_montant_ht,      fprof.`timbre` AS fact_timbre,      fprof.`TVA` AS fact_TVA,      fprof.`autre_taxe` AS fact_autre_taxe,      client.`Nclient` AS client_Nclient,      client.`Raison_sociale` AS client_Raison_sociale,      client.`adresse` AS client_adresse,      client.`NRC` AS client_NRC,      client.`Date_RC` AS client_Date_RC,      client.`Lieu_RC` AS client_Lieu_RC,      client.`I_Fiscal` AS client_I_Fiscal,      client.`N_article` AS client_N_article       FROM      `client` client INNER JOIN `fprof` fprof ON client.`Nclient` = fprof.`Nclient` WHERE fprof.nfact ='"+txt_nfact.getText()+"'";
                 //JOptionPane.showMessageDialog(null, "Proforma");
                // JOptionPane.showMessageDialog(null, txt_domaine_actvite);
                break;
            
        }
            // String report ="C:\\outil_dev\\report2_v2.Jrxml";
            imprime();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur impression " + e.getMessage());
            }    
        
        
    }//GEN-LAST:event_btn_imprimerActionPerformed

    
private void imprime(){
    try{
        String query_a ="select * from activite";
            Rs=St.executeQuery(query_a);
             if (Rs.next()) { 
                txt_domaine_actvite = Rs.getString("domaine_activite");                
                txt_sous_domaine= Rs.getString("sous_domaine");
                txt_raison_sociale_v=Rs.getString("raison_sociale");
                txt_adresse = Rs.getString("adresse");
                txt_commune = Rs.getString("commune");
                txt_wilaya = Rs.getString("wilaya");
                txt_tel_fixe = Rs.getString("tel_fixe");
                txt_tel_port = Rs.getString("tel_port");
                txt_email = Rs.getString("e_mail");
                txt_nrcv = Rs.getString("nrc");
                txt_nis = Rs.getString("nis");
                txt_nart = Rs.getString("nart");
                txt_ident_fiscal = Rs.getString("ident_fiscal");
                txt_banq = Rs.getString("banq"); 
                txt_entete_bon = Rs.getString("entete_bon"); 
                //JOptionPane.showMessageDialog(null, txt_entete_bon);
             }
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            //JOptionPane.showMessageDialog(null, txt_entete_bon);
            HashMap hm = new HashMap();
            hm.put("fact_spell", exp_spell);        
            hm.put("domaine_activite_p",txt_domaine_actvite);
            hm.put("sous_domaine_p",txt_sous_domaine);
            hm.put("raison_sociale_p",txt_raison_sociale_v);
            hm.put("adress_p",txt_adresse);
            hm.put("commune_p",txt_commune);
            hm.put("wilaya_p",txt_wilaya);
            hm.put("tel_fixe_p",txt_tel_fixe);
            hm.put("tel_port_p",txt_tel_port);
            hm.put("e_mail_p",txt_email);
            hm.put("nrc_p",txt_nrcv);
            hm.put("nis_p",txt_nis);
            hm.put("art_p",txt_nart);
            hm.put("ident_fiscal_p",txt_ident_fiscal);
            hm.put("banq_p",txt_banq);
            hm.put("entete_p",txt_entete_bon);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr,hm,cnx);               
            JasperViewer.viewReport(jp, false); 
            //JasperExportManager.exportReportToPdfFile(jp, "E:\\habib\\sample_report.pdf");
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur impression " + e.getMessage());
            } 
}
    
    private void btn_chercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_chercherFocusLost
        chercher();
    }//GEN-LAST:event_btn_chercherFocusLost

    private void btn_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quitterActionPerformed

    private void btn_impression_ptit_formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_impression_ptit_formatActionPerformed
        try {
            jd = JRXmlLoader.load("C:\\outil_dev\\report_smal_bl.jrxml");
           // jd = JRXmlLoader.load("report_smal_bl.jrxml");
            sql = "SELECT bl.`NFact` AS fact_NFact,      bl.`Nclient` AS fact_Nclient,      bl.`date_fact` AS fact_date_fact,      bl.`montant_ht` AS fact_montant_ht,      bl.`timbre` AS fact_timbre,      bl.`TVA` AS fact_TVA,      bl.`autre_taxe` AS fact_autre_taxe,      client.`Nclient` AS client_Nclient,      client.`Raison_sociale` AS client_Raison_sociale,      client.`adresse` AS client_adresse,      client.`NRC` AS client_NRC,      client.`Date_RC` AS client_Date_RC,      client.`Lieu_RC` AS client_Lieu_RC,      client.`I_Fiscal` AS client_I_Fiscal,      client.`N_article` AS client_N_article,  bl.`nbc` AS fact_nbc, bl.`date_bc` AS fact_date_bc, bl.`nom_preneur` AS fact_nom_preneur        FROM      `client` client INNER JOIN `bl` bl ON client.`Nclient` = bl.`Nclient` WHERE bl.nfact ='" + txt_nfact.getText() + "'";                    
             imprime();
        } catch  (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table Clients\n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_impression_ptit_formatActionPerformed

    private void btn_impression_de_bonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_impression_de_bonActionPerformed
        try {
            jd = JRXmlLoader.load("C:\\outil_dev\\report_ticket.jrxml");
           // jd = JRXmlLoader.load("report_ticket.jrxml");
            //jd = JRXmlLoader.load("C:\\outil_dev\\report_bon.jrxml");
            // jd = JRXmlLoader.load("C:\\outil_dev\\report_ext_smal_bl.jrxml");
            sql="SELECT bl.`NFact` AS fact_NFact, bl.`Nclient` AS fact_Nclient,bl.`date_fact` AS fact_date_fact, bl.`montant_ht` AS fact_montant_ht,bl.`timbre` AS fact_timbre,     bl.`TVA` AS fact_TVA,     bl.`autre_taxe` AS fact_autre_taxe, client.`Nclient` AS client_Nclient,client.`Raison_sociale` AS client_Raison_sociale, client.`adresse` AS client_adresse, client.`NRC` AS client_NRC, client.`Date_RC` AS client_Date_RC,     client.`Lieu_RC` AS client_Lieu_RC, client.`I_Fiscal` AS client_I_Fiscal,client.`N_article` AS client_N_article,bl.`nbc` AS fact_nbc, bl.`date_bc` AS fact_date_bc, bl.`nom_preneur` AS fact_nom_preneur, article.`designation` AS designation, detail_bl.`Narticle` AS detail_bl_Narticle, detail_bl.`Qte` AS detail_bl_Qte, detail_bl.`tva` AS detail_bl_tva, detail_bl.`prix` AS detail_bl_prix, detail_bl.`total_ligne` AS detail_bl_total_ligne FROM     `client` client INNER JOIN `bl` bl ON client.`Nclient` = bl.`Nclient`,`article` article,     `detail_bl` detail_bl WHERE detail_bl.`Narticle`=article.`Narticle` AND detail_bl.`NFact`=bl.`NFact` and bl.nfact ='" + txt_nfact.getText() + "'";
            //sql = "SELECT bl.`NFact` AS fact_NFact,      bl.`Nclient` AS fact_Nclient,      bl.`date_fact` AS fact_date_fact,      bl.`montant_ht` AS fact_montant_ht,      bl.`timbre` AS fact_timbre,      bl.`TVA` AS fact_TVA,      bl.`autre_taxe` AS fact_autre_taxe,      client.`Nclient` AS client_Nclient,      client.`Raison_sociale` AS client_Raison_sociale,      client.`adresse` AS client_adresse,      client.`NRC` AS client_NRC,      client.`Date_RC` AS client_Date_RC,      client.`Lieu_RC` AS client_Lieu_RC,      client.`I_Fiscal` AS client_I_Fiscal,      client.`N_article` AS client_N_article,  bl.`nbc` AS fact_nbc, bl.`date_bc` AS fact_date_bc, bl.`nom_preneur` AS fact_nom_preneur        FROM      `client` client INNER JOIN `bl` bl ON client.`Nclient` = bl.`Nclient` WHERE bl.nfact ='" + txt_nfact.getText() + "'";                    
             imprime();
        } catch  (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table Clients\n" + e.getMessage());
        } 
    }//GEN-LAST:event_btn_impression_de_bonActionPerformed

    private void Update_Table_Factures() {

        try {            
            String sql = "select F.id as \"Seq.\", F.Narticle as \"Code Article\", A.Designation as \"Designation\", F.prix as \"Prix Unitaire\", A.tva as \"TVA\", F.qte as \"Quantité\", F.total_ligne as \"Prix Total\"  from facture_temp AS F, article AS A where F.narticle=A.narticle order by F.id" ;                      
            tm = new MyTableModel(sql, base);
            Table_Factures.setModel(tm);
            Table_Factures.setDefaultRenderer(Double.class, new TKMntRenderer());
             } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "avec la table Clients\n" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public static void rappel_facture(final String par, final String det, final String mas, final String bas){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rappel_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rappel_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rappel_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rappel_facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rappel_facture(par,det,mas,bas).setVisible(true);
            }
        });
    }
    
    
    
    // Déclaration des variables
    private Statement St;
    private ResultSet Rs;
    public Connection cnx;
    public String parametre, fichier_detail, fichier_master;
    public String txt_domaine_actvite,txt_sous_domaine,txt_raison_sociale_v,txt_adresse,txt_commune,txt_email,txt_wilaya;
    public String txt_tel_fixe,txt_tel_port,txt_nrcv,txt_nis,txt_nart,txt_ident_fiscal,txt_banq,txt_query,exp_spell;
    public String sql,query, base,titre,txt_entete_bon;
    public JasperDesign jd ;
    int j, int_nfact;
    double mnt;
    MyTableModel tm;
    Double stot_ligne =0.00, prix_unitaire=0.00, add1_d=.00, timbre = 0.00, tva = 0.00, xtot_ht=0.00, xtot_tva=0.00;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Factures;
    private javax.swing.JButton btn_chercher;
    private javax.swing.JButton btn_impression_de_bon;
    private javax.swing.JButton btn_impression_ptit_format;
    private javax.swing.JButton btn_imprimer;
    private javax.swing.JButton btn_quitter;
    private javax.swing.JButton btn_supprimer;
    private com.toedter.calendar.JDateChooser date_fact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_code_cli;
    private javax.swing.JTextField txt_nfact;
    private javax.swing.JTextField txt_numero_fact;
    private javax.swing.JTextField txt_prix_tot;
    private javax.swing.JTextField txt_raison_sociale;
    private javax.swing.JTextField txt_s_total;
    private javax.swing.JTextField txt_timbre;
    private javax.swing.JTextField txt_total_tva;
    // End of variables declaration//GEN-END:variables
}
