/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author IT
 */
public class test_double extends javax.swing.JFrame {

    /**
     * Creates new form test_double
     */
    public test_double() {
        initComponents();
      Date dt = new Date();
      SimpleDateFormat df = new SimpleDateFormat( "yyyy-MM-dd");
      JOptionPane.showMessageDialog(null,df.format(dt));
     
        // 1. Get default keys
      Set<AWTKeyStroke> ftk = new HashSet<AWTKeyStroke>(
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .getDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));

// 2. Add our key
       ftk.add(KeyStroke.getKeyStroke("ENTER"));


// 3. Set new keys
KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .setDefaultFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, ftk);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_designation = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jfdate = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2))
                            .addComponent(jButton1))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jfdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // DecimalFormat patternFormatter = new DecimalFormat ("############.00");
        
        //String xmnt=patternFormatter.format(Double.parseDouble(txt_nombre.getText().toString()));
        double mnt=Double.parseDouble(txt_nombre.getText().toString());
        //JOptionPane.showMessageDialog(null,xmnt);
        JOptionPane.showMessageDialog(null,mnt);
        //String xmnt=patternFormatter.format(mnt).replace(",", ".");
        //txt_designation.setText(xmnt);
        //double mnt1=Double.parseDouble(txt_designation.getText().toString());
        //JOptionPane.showMessageDialog(null,xmnt);
        
        //JOptionPane.showMessageDialog(null,mnt1);
        String exp_spell = Numb_to_Spell.spell(mnt, "");
        JOptionPane.showMessageDialog(null,exp_spell);
      
          
      txt_designation.setText(exp_spell);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {      
                               String[] prompts = { "Banque :", "N°Chèque :"};          
          
                               String [] message = { "", ""};
                               //JOptionPane.showInputDialog(null, message, "Information Bancaire", JOptionPane.OK_CANCEL_OPTION,null,fields,"");
                             // JOptionPane.showInputDialog(null, fields, "Information Bancaire", JOptionPane.OK_CANCEL_OPTION);
                                    
                               String[] x = MultiInputPane.showMultiInputDialog(null,prompts, "Habib");
                               JOptionPane.showMessageDialog(null,x);  

            
            
            
                                 Object[] options = {"Oui, Svp!","Non, Merci"};                 
                                 int r = JOptionPane.showOptionDialog(null, " Etes vous sur de vouloir Supprimer ?", "Confirmation",  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null, options,options[1]);            
            
 //int r =JOptionPane.showOptionDialog(null, "Voulez vous confirmer votre choix","Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
      //     int s = JOptionPane.showConfirmDialog(null,  "Voulez vous confirmer votre choix","Confirmation",JOptionPane.YES_NO_OPTION);
          
          
        
           
           
           
            //if (r == 0) {    
               JOptionPane.showMessageDialog(null, r);
              /* String sql = "insert into facture  select *  from facture_temp ";
                     St.executeUpdate(sql);
               nettoyer_facture.nettoyer_facture();
                      sql = " delete from "+fichier_detail+" where nfact ='"+txt_nfact.getText()+"'" ;
                     St.executeUpdate(sql);  
                      sql = " delete from "+fichier_master+" where nfact ='"+txt_nfact.getText()+"'" ;
                     St.executeUpdate(sql);
            sql ="truncate table facture_temp";
            St.executeUpdate(sql);
            vider_champs();
            txt_nfact.setText("");
               */           
           // } else {
            //    JOptionPane.showMessageDialog(null, r);
             //}
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }  
     
                             
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        try {      
       
   Object[] options = {"Oui, Svp!","Non, Merci"};                 
   int r = JOptionPane.showOptionDialog(null, " Etes vous sur de vouloir Supprimer ?", "Confirmation",  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null, options,options[1]);            
       JOptionPane.showMessageDialog(null, r);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }          
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyTyped
       try {      
       
   Object[] options = {"Oui, Svp!","Non, Merci"};                 
   int r = JOptionPane.showOptionDialog(null, " Etes vous sur de vouloir Supprimer ?", "Confirmation",  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null, options,options[1]);            
       JOptionPane.showMessageDialog(null, r);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }   
        
    }//GEN-LAST:event_jButton2KeyTyped

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
 try {      
       
   Object[] options = {"Oui, Svp!","Non, Merci"};                 
   int r = JOptionPane.showOptionDialog(null, " Etes vous sur de vouloir Supprimer ?", "Confirmation",  JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null, options,options[1]);            
       JOptionPane.showMessageDialog(null, r);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur dans la table\n" + e.getMessage());
            }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test_double.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test_double.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test_double.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test_double.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test_double().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField jfdate;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
